### ISSUE TITLE
Implement the Resolution hack

### ISSUE THREAD

**Issue by heinermann** [bwapi/bwapi#291]
_From [AHeinerm](https://code.google.com/u/AHeinerm/) on November 12, 2010 17:46:23_

For me to do.

_Original issue: http://code.google.com/p/bwapi/issues/detail?id=293_

**Comment by KYSXD** [comment]
It's possible to resize the game layer from 640x400 to 640x480?

I was playing around with some files in order to achieve this [hud](http://www.moddb.com/members/kysxd/images/hud-20-wip1), but the engine doesn't render [as i want](http://www.moddb.com/members/kysxd/images/weird).

**Comment by heinermann** [comment]
Since there is already a working hack compatible with BWAPI, there is no reason to create a new resolution hack (which requires some effort).

If anyone feels strongly about this then they will need to take on the work needed to write it.
