### ISSUE TITLE
"Local PC" does not work in Win 7 x64

### ISSUE THREAD

**Issue by heinermann** [bwapi/bwapi#294]
_From [shaoy...@gmail.com](https://code.google.com/u/116855039057169093527/) on November 16, 2010 22:51:45_

What steps will reproduce the problem? 1. Run two instances in multiple instance mode
2. Enter "Local PC" network mode
3. Create a game in one instance What is the expected output? What do you see instead? The second instance cannot see the created game to enter. What version of the product are you using? On what operating system? BWAPI Beta 3.2 with Chaoslauncher 0.5.4.1, W-Mode 1.02 on Win 7 x64 Please provide any additional information below.

_Original issue: http://code.google.com/p/bwapi/issues/detail?id=296_

**Comment by Aralox** [comment]
Hi heinermann, not sure if this is the best place to post this, but I accidentally specified the wrong starcraft folder when installing BWAPI, and was unable to re-install it properly as I think the registry entry was already set. So I copied over the bwapi-data folder to the correct Starcraft directory, but it wouldn't work (Local PC does not show up) until I also copied over the SNP_DirectIP.snp file.
Also, I had to hunt around for a while before figuring out how to use Java bots (from SSCAIT), I think it'd be really helpful to mention in the BWAPI readme that all you have to do is rename the downloaded zip file to a jar file (I know it's not directly related to this project, but it would really help out beginners like me). 
Thanks for your work, and looking forward to the 1.18/remastered version of BWAPI.

**Comment by N00byEdge** [comment]
@Aralox Yes this is very much the wrong place.
Set your Starcraft directory in Chaoslauncher settings.

**Comment by Aralox** [comment]
Apologies. I only posted here because I spent some time searching for "Local PC not working" and only figured out the solution because of a comment in this issue. Also, I did try changing that setting "with admin privs", but it did not automatically create /transfer the needed snp file.
