### ISSUE TITLE
Compatibility between bwapi server and client process

### ISSUE THREAD

**Issue by heinermann** [bwapi/bwapi#301]
_From [tren...@gmail.com](https://code.google.com/u/100267150710479896093/) on November 21, 2010 16:28:43_

When a connection to a bwapi client process is established one should check for compatibility (this should probably also be done for the modules?).

When the BWAPI.dll and other files that go into the starcraft directory are compiled from a different svn revision number (or another compiler) there might occur problems right?

I used the original bwapi 3.3 files from the downloadable package and installed them into the starcraft directory. I then compiled bwapi from svn with VC++ 2010, so that i could use the generated BWAPI.lib with Visual Studio 2010 (the provided one can't be used with VC++ 2010 because of incompatibility with the compiler).
The bwapi client compiled and executed successfully and everything seemed to be fine and work, but still, there is no guarantee for that or is there?

_Original issue: http://code.google.com/p/bwapi/issues/detail?id=303_

**Comment by heinermann** [comment]
In order to complete this issue, client/server should use their own versioning system and ditch the revision number.

**Comment by heinermann** [comment]
See #584 . The compatibility issues with different compilers will not be dealt with here. You will need to recompile BWAPIClient, BWAPILIB, etc for your compiler.

**Comment by heinermann** [comment]
Fixed in e0893bc18d321294ea14.

**Comment by chriscoxe** [comment]
As far as client-server and/or server-client compatibility is concerned, is the plan that the version-checking logic will treat every release as incompatible with the penultimate release, or is the plan that the version checking logic will only treat them as incompatible if the client-server are really incompatible?

If the latter is true, as far as client-server and/or server-client compatibility is concerned, please could someone clarify whether there are any plans to make 4.2.0 compatible with old versions (e.g. 4.1.2, 4.1.1 Beta, 4.1.0 Beta, 4.0.1 Beta, 4.0.0 Beta)?  Looking at e0893bc it appears that 4.2.0 is going to be incompatible with all older versions unless special cases are added to support them.  Ignoring the change made in this ticket and the revision checking logic of earlier versions, I have no idea when the last time a change was made that really broke client-server compatibility.  Maybe it could be made compatible with old versions as far as 4.0.0 Beta?  Similarly if this kind of change is merged into version 3.X.
