### ISSUE TITLE
get Minerals

### ISSUE THREAD

**Issue by heinermann** [bwapi/bwapi#415]
_From [snake__p...@hotmail.com](https://code.google.com/u/115226883429139857396/) on November 16, 2011 17:57:35_

Actually i m working in jnibwapi. however i need to do some stuff in bwapi. I want to get the current minerals and gas of the game. So i found the method minerals() in the class player. I tried to do something like that

BWAPI::Player\* player;

int minerals = player->minerals();

in debugging i got no errors, but i cant run the game. Any idea?

_Original issue: http://code.google.com/p/bwapi/issues/detail?id=417_

**Comment by verystrongjoe** [comment]
what if I want to know the total minerals that I have mined?

**Comment by dgant** [comment]
@verystrongjoe https://bwapi.github.io/class_b_w_a_p_i_1_1_player_interface.html#a709df7d0fe07f4caf6e18d61f3b7b9e9

BWAPI::PlayerInterface::gatheredMinerals
