### ISSUE TITLE
Game speed randomly fluctuates in long series of matches

### ISSUE THREAD

**Issue by drTentacle** [bwapi/bwapi#502]
SC: 1.16.1
Chaoslauncher
JNIBWAPI
While gathering statistic data for my bot evaluation. I've noticed the game speed in the long series of games randomly fluctuates without evident reason. I let the bot run tens or hundred matches unattended (correctly restarting after each match). Despite I set gameSpeed at the beginning of each match to 0 (using JNIBWAPI   .setGameSpeed(0)), meaning not to stall at all between the frames, I've regularly found the game slowed by magnitude - prolonging one game match from tens of seconds to hours.  

This was not due to some resource dependent computation or similar reason. Simply delay between the frames was set to some (random) high value. Only workaround I have found was sending command bwapi.setGameSpeed(0) every 500 frames, which "solved" the problem. 
AFAIK there is no mention of such problem in documentation/web.

**Comment by heinermann** [comment]
It may perhaps be the result of minimizing and restoring the Starcraft window.
