### ISSUE TITLE
BWAPI::Broodwar->hasPath(pos1, pos2) returns false negatives

### ISSUE THREAD

**Issue by krasi0** [bwapi/bwapi#515]
BWAPI ver 4.
Example: 
map (4)Andromeda.scx
pos1	{x=3526 y=972 }	BWAPI::Point<int,1>
pos2{x=3076 y=995 }	BWAPI::Point<int,1>

where pos1 is the position of a Terran Goliath (->getPosition())

**Comment by heinermann** [comment]
It seems this may be intended. The position (3526, 972) is actually on an unwalkable part of the top right ramp and is also part of a disconnected region.

![screenshot from 2015-01-06 21 43 40](https://cloud.githubusercontent.com/assets/1966366/5639970/1e6c8cd4-95ed-11e4-8cc2-4f893d58a155.png)

**Comment by krasi0** [comment]
I understand that it's obviously non-walkable, but at the same time, it's reported as the position of a land unit (in this case - a Goliath), so one is not able to get a correct result about whether a unit can reach an obviously reachable position using hasPath()... 
My workaround is to "round()" such positions to the nearest walkable one, but I don't believe that's the optimal solution.

**Comment by heinermann** [comment]
So in this case `Broodwar->hasPath(goliath->getPosition(), target);` is the correct behaviour, and `goliath->hasPath(target);` will have the new behaviour.

**Comment by krasi0** [comment]
Perhaps related to the above open question:
On Andromeda, hasPath() returns true for the following two positions:
+		pos1	{x=2672 y=3760 }	BWAPI::Point<int,1>
+		pos2	{x=2051 y=3641 }	BWAPI::Point<int,1>

The second one is obviously not walkable
