### ISSUE TITLE
Reset timeout dialog

### ISSUE THREAD

**Issue by albertouri** [bwapi/bwapi#516]
Is it possible to reset the timeout dialog in a multiplayer game?
I'm doing some experiments and sometimes my bot spends too much time thinking and the other player kick my out because I consume all the timeout.

**Comment by heinermann** [comment]
If you mean remotely, then no. But we can possibly specify if bots should automatically drop the other player from the game or not with a configuration option.

Would that work for you?

**Comment by albertouri** [comment]
Yes, that would work  :smile:
