### ISSUE TITLE
Sometimes units with ->getID() == -1 are returned when calling getOrderTarget() on a player unit

### ISSUE THREAD

**Issue by krasi0** [bwapi/bwapi#517]
Oddly enough the returned unit belongs to the enemy player, but its race is of type of the BWAPI player, e.g. in a T (BWAPI player) vs P (opponent),
when called on an own Goliath unit ->getOrderTarget() might occasionally a Vulture Spider Mine, with getID() == -1 and belonging to the opponent.

Similar issues occur sometimes, when calling getUnitsOnTile(). For example a Dragoon unit might be reported as belonging to the BWAPI player (Terran) in a TvP game.

**Comment by heinermann** [comment]
I'm not sure what to make of this. Can you repro it using the map editor to place all the necessary units?

**Comment by krasi0** [comment]
Not really. It happens during longer games. You might just rung a game with
a few AI players and put some break points for when this happens.

On Mon, Apr 27, 2015 at 2:15 PM, Adam Heinermann <notifications@github.com>
wrote:

> I'm not sure what to make of this. Can you repro it using the map editor
> to place all the necessary units?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bwapi/bwapi/issues/517#issuecomment-96626666>.
>



-- 
BR

**Comment by heinermann** [comment]
Was this not fixed in 0954440b3048e9ea72cc32b587b7df50210ef29f ?
