### ISSUE TITLE
Random crashes during long, repetitive game sessions.

### ISSUE THREAD

**Issue by krasi0** [bwapi/bwapi#526]
I am running my AI module (BWAPI 4) in many games in a row. For example, BGH, FFA, vs 3 opponents and occasionally Broodwar crashes. In VS, I see the stack frames similar to the one in attached screenshot.

Do you guys think, that it's my bot's source somehow corrupting the memory or is it rather a legit Broodwar crash?
![snapshot4](https://cloud.githubusercontent.com/assets/6185019/5218840/730006a6-7651-11e4-8934-a3a60ae3a765.png)
![snapshot5](https://cloud.githubusercontent.com/assets/6185019/5220831/a35a2510-766b-11e4-8d24-cef1be94a0b6.png)

**Comment by heinermann** [comment]
If you're using modded game files then the crash can be attributed to them.

Have you encountered the crash at all recently?

**Comment by krasi0** [comment]
Yes, it still occurs.

On Thu, Apr 9, 2015 at 9:52 AM, Adam Heinermann <notifications@github.com>
wrote:

> If you're using modded game files then the crash can be attributed to them.
>
> Have you encountered the crash at all recently?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bwapi/bwapi/issues/526#issuecomment-91142967>.
>



-- 
BR

**Comment by heinermann** [comment]
Are you using modded game files?

**Comment by krasi0** [comment]
I've encountered it less frequently lately when using modded files. Let's close the issue for now
