### ISSUE TITLE
BWAPI::Broodwar->canBuildHere() false positives

### ISSUE THREAD

**Issue by krasi0** [bwapi/bwapi#537]
The method tends to return true when checking whether building an addon is possible at an obstructed building site. 

For example, given a non-lifted factory with a non-lifted barracks to its right, the method returns true when called with both the tile position of the factory and  with the tile position where the addon would appear. The factory unit itself is also passed as the third parameter.

**Comment by heinermann** [comment]
Fixed in 7ead3d1ab94e863666, please verify.
