### ISSUE TITLE
Function setScreenPosition() is unable to reach the ~80-90 lowest pixels on map (BWAPI 3.7)

### ISSUE THREAD

**Issue by Plankton555** [bwapi/bwapi#540]
This occurs under BWAPI 3.7. It may or may not have been reported and fixed yet, I haven't been able to test it under BWAPI 4.0.

### Description

It is impossible to move the camera/screen to the lowest part of the map using the function `BroodWar->setScreenPosition()`. About 80-90 pixels cannot be reached.

### How to reproduce

Call the function `BroodWar->setScreenPosition(5000, 5000)`. The position {5000, 5000} is outside the map (most maps at least) and the camera should instead be positioned in the lower right corner (as close to the position {5000, 5000} as possible). What happens is instead that the camera is moved as far as possible to the right side of the map, but not as far as possible to the bottom side of the map. The camera is positioned about 80-90 pixels above the lowest possible position on the map. See attached image:

![bwapi_bug](https://cloud.githubusercontent.com/assets/1454000/5692034/45f34cb2-98e4-11e4-97e8-ff847281a736.png)

### Possible explanation of this?
The Brood War game window is 640x480 pixels, but the lowest portion of this is made up of the GUI. This means that the actual game screen is something like 640x390 pixels large. I would guess that `BroodWar->setScreenPosition()` makes sure that the camera is not moved outside the map by setting its maximum y position to be the bottom border of the map minus 480. Now since the height of the actual game screen (without GUI) is about 80-90 pixels smaller than 480, the camera gets positioned higher up than it should.

The code in the file `GameImpl.cpp` (see link: https://github.com/bwapi/bwapi/blob/master/bwapi/BWAPI/Source/BWAPI/GameImpl.cpp ), row 203, seems to add 80 pixels to the game screen on the y axis. Could this have something to do with it?

**Comment by heinermann** [comment]
Confirmed happens in 332b5fe0cfc4a738966ca30025560b2da11a8b34.
