### ISSUE TITLE
Filter::IsEnemy not working properly

### ISSUE THREAD

**Issue by albertouri** [bwapi/bwapi#542]
In a replay game (with observers). The filter isEnemy (Filter::CanAttack && Filter::IsEnemy) always returns 0 units. While (Filter::CanAttack && Filter::GetPlayer != unit->getPlayer()) works fine.

**Comment by heinermann** [comment]
This is because IsEnemy works by checking if the unit is an enemy of the BWAPI player. In a replay, there is no BWAPI player, so it follows that there are no units that belong to an enemy of the BWAPI player.

**Comment by albertouri** [comment]
Ok, it makes sense. Maybe an explanation in the documentation would help to avoid misunderstandings ;)

**Comment by EHadoux** [comment]
Sorry to reopen that but it makes little sense to me.
When doing ```unit->getClosestUnit(Filter::isEnemy)```, I expect the test to be an enemy of the unit, not of the player (in this case an observer).
I guess changing that would be too much but do you have another solution to have this behavior?
