### ISSUE TITLE
Launcher Crashes using BWAPI_PluginInjector.bwl

### ISSUE THREAD

**Issue by elementalest** [bwapi/bwapi#543]
The chaoslauncher crashes when using the BWAPI_PluginInjector.bwl file in either the plugin folder or the exe location of the launcher. BWAPI.dll was also placed in the plugins folder and the launcher folder with no success.

If an older version of the bwl file and BWAPI.dll are placed in the same directory as the launcher exe, the launcher runs and the Client is able to connect.

Edit: This is on the dev branch

**Comment by elementalest** [comment]
I realised that i need to have the 'bwapi-data' folder in my actual star craft game folder. When i copied the folder from the Release_Binary folder to my star craft game folder and used the new BWAPI_PluginInjector.bwl in the plugin folder, everything ran fine.

**Comment by krasi0** [comment]
Hehe. So much debugging and then... 😊

**Comment by elementalest** [comment]
It's always something so simple like that. Keeps us humble I guess :D
