### ISSUE TITLE
Event UnitComplete being sent in the wrong time (at unit creation) in client mode sometimes.

### ISSUE THREAD

**Issue by Predelnik** [bwapi/bwapi#553]
Example test for this is really easy. Just add followng lines to switch on event type in ExampleBWAIClient:

    case EventType::UnitComplete:
        assert (e.getUnit ()->isCompleted ());
        break;

and include assert.h, connect client with debugger to sc, start new single player game and do "Restart Mission" a couple of times. After several times assert will most likely trigger.

Beside that I noticed the following:
- Such problem seemingly never happens on the first game after starting Starcraft
- In subsequent games sooner or later such problem will occur most likely during the game.

I'll probably try to study and debug a bit further why this happens, I will add it as a comment if I'll find something.

**Comment by Predelnik** [comment]
At first I would like to point out that it happens also with dll modules so it's not a problem with client/server.

And it seems like I was able to narrow down the issue but I may as well be wrong and how to correct it is up to you of course, there is 3 functions being called in `GameImpl::UpdateUnits()`

      computeUnitExistence();
      computePrimaryUnitSets();
      extractUnitData();

The first one call `updateInternalData` for each alive `UnitImpl` which as I understand updates the stuff that stored outside `UnitData` at `self` pointer. `updateData` which updates `UnitData` is called only in the third one.

But in the second one there's check which determines `unitComplete` event generation based on the following condition:

    if ( !u->wasCompleted && u->isCompleted() )

And it's using `isCompleted()` which actually checks for variable `isCompleted` in `UnitData` which is not updated at this point. The rest of the checks seems to be only about inernal data. So basically when games after the first one start, in my understanding it may be incorrect data from previous games.

Changing this check to `u->_isCompleted` (which seems to be internal data counterpart of `UnitData` `isCompleted`) seemingly works and fixes the problem.

**Comment by krasi0** [comment]
Yeah, it could potentially be a missing clean up of old data. BTW, PRs are
encouraged, so if you have a fix, please go ahead and create one. It will
be reviewed and merged. :)

On Sat, Feb 7, 2015 at 4:11 PM, Sergey Semushin <notifications@github.com>
wrote:

> At first I would like to point out that it happens also with dll modules
> so it's not a problem with client/server.
>
> And it seems like I was able to narrow down the issue but I may as well be
> wrong and how to correct it is up to you of course, there is 3 functions
> being called in GameImpl::UpdateUnits()
>
>   computeUnitExistence();
>   computePrimaryUnitSets();
>   extractUnitData();
>
> The first one call updateInternalData for each alive UnitImpl which as I
> understand updates the stuff that stored outside UnitData at self
> pointer. updateData which updates UnitData is called only in the third
> one.
>
> But in the second one there's check which determines unitComplete event
> generation based on the following condition:
>
> if ( !u->wasCompleted && u->isCompleted() )
>
> And it's using isCompleted() which actually checks for variable
> isCompleted in UnitData which is not updated at this point. The rest of
> the checks seems to be only about inernal data. So basically when games
> after the first one start, in my understanding it may be incorrect data
> from previous games.
>
> Changing this check to u->_isCompleted (which seems to be internal data
> counterpart of UnitData isCompleted) seemingly works and fixes the
> problem.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bwapi/bwapi/issues/553#issuecomment-73367993>.
>



-- 
BR

**Comment by heinermann** [comment]
:+1:  for pull request so I don't have to be the only one that appears in the commit log. :cat:

**Comment by heinermann** [comment]
So is this fixed?

**Comment by Predelnik** [comment]
I believe in dev branch yes, not sure why Krasi didn't close it :)

**Comment by krasi0** [comment]
I was waiting for some feedback from potential testers. I guess, since no
one has complained so far we can close it
