### ISSUE TITLE
AI Client) unit->exists() returns true in onUnitDestroy()

### ISSUE THREAD

**Issue by krasi0** [bwapi/bwapi#555]
Note: this issue doesn't occur when using an AI Module.

**Comment by Predelnik** [comment]
Seemingly, moving `lastEvadedUnits = evadeUnits` line to the bottom of `computePrimarySets` fixes this issue, but then I don't understand very well how `lastEvadedUnits ` could be different from `evadeUnits` when `Server::update` will be called and why just `evadeUnits` couldn't be used instead.

**Comment by heinermann** [comment]
I think it relates to why we used evadeUnits in the first place.
Potentially, using the previously misunderstood field in CUnit that
guarantees uniqueness could fix this issue among others and improve
performance. I'll take a deeper look possibly on Friday.

**Comment by heinermann** [comment]
I literally have no idea what the purpose of lastEvadedUnits is

**Comment by krasi0** [comment]
Then let's try without it? :)

On Fri, Feb 27, 2015 at 7:00 PM, Adam Heinermann <notifications@github.com>
wrote:

> I literally have no idea what the purpose of lastEvadedUnits is
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bwapi/bwapi/issues/555#issuecomment-76441235>.
>



-- 
BR
