### ISSUE TITLE
alwaysZero1 in MovementFlags.h

### ISSUE THREAD

**Issue by BoomerangAide** [bwapi/bwapi#557]
Hi,

I'm working on a GPTP fork, and trying to upgrade it with some data of BWAPI (when the code is similar enough).
I saw that in " bwapi/bwapi/BWAPI/Source/BW/MovementFlags.h " the bit for 0x80 is named alwaysZero1, something I would assume to mean that this bit is always 0.
But in GPTP, there's this piece of code in hooks\spider_mine.cpp:

		//Don't attack hovering units
		if (units_dat::MovementFlags[target->id] == (0x01 | 0x40 | 0x80))  //Note: This is not a mistake; SC actually uses a "==" comparison to check flags (I know it's a WTF).
		  return false;

So I'm wondering, is that GPTP code mistaken (it would never be triggered if 0x80 is always 0), or is the name alwaysZero1 in BWAPI misleading?

**Comment by heinermann** [comment]
The fact that it's called alwaysZero1 means it's unknown but hasn't been observed to change. If it were known it would have been called either `somethingRelevant` or `unused1`.

**Comment by heinermann** [comment]
The file being discussed is [here](https://github.com/bwapi/bwapi/blob/master/bwapi/BWAPI/Source/BW/MovementFlags.h).

This is actually unrelated to your original code snippet. I just realized it, but you're looking at movement flags in `units.dat` (unit type). This file is specifically for the [movementFlags field](https://github.com/bwapi/bwapi/blob/master/bwapi/BWAPI/Source/BW/CUnit.h#L59) in the CUnit definition.
