### ISSUE TITLE
Some suggestions for "save_replay" option improvement

### ISSUE THREAD

**Issue by Predelnik** [bwapi/bwapi#561]
I implemented some of these changes locally and I want to question is these improvements are good or not to be pushed to bwapi and also to provide some reasoning for them:

1. Add variable to contain game result for `save_replay`. For example I added `%GAMERESULT%` variable which equals `win` in case of winning and `loss` in case of losing. Maybe it could also be name of winning player, but personallly I like the simple win/loss variant better.

  _Usage_: after playing a lot of games with no gui on max speed it allows quickly to find replays where bot lost and watch them ignoring others, also adds a free way to quickly glance over the statistics. There could be other workarounds probably, like finding it from replays content or making bot store indexes of lost games but it seems like this one is the simplest and could be done without much fuss.

2.  For default starcraft AI I think that `%ENEMYNAME%` should be always the same, I don't believe that anyone have much interest against which tribe/brood they were playing :) Taking example from default Starcraft autoreplay it could be just named "Comp"

3. Not exactly about `save_replay` but I guess it's connected. There are options for choosing random race from any pair of them randomized by bwapi before the game. But I think that technically there should also be option to select out of all 3 randomized by bwapi and it differs from `Random` in the following:

      * Bots will play differently knowing the race they play against, so technically it will be totally different test case
      * `save_replay` will write the correct race letter in that case and not U as in Unknown :)

  Since it's mostly concerning default AI it's not that significant of course but I think such option could be useful. Suggested name: "RandomTPZ" similar to 2-race randoming options.

**Comment by krasi0** [comment]
All three points seem useful to me

**Comment by heinermann** [comment]
1. %GAMERESULT% is good. 

2. %ENEMYNAME% would be Computer (do we even have ENEMYNAME? It's not listed in the config wiki.).

In %ENEMYNAMES% it would use Comput, but then it would be ComputComputComputComput if you're facing many of them (although the replay file name is too large at this point), I'm not sure how that would work out.

3. RandomTPZ is fine.

**Comment by Predelnik** [comment]
Yeah I meant %ENEMYNAMES%, well even currently it would most likely exceed max replay name length in case of many players so it's probably usable only for people who play 1vs1 and in that case "Comp" or "Comput" will fit better than generated name from the game (like Kel-Morian Combine, Garm Brood etc etc) cut to 6 symbols.

**Comment by Predelnik** [comment]
While figuring out why my implementation of RandomTPZ wasn't working I noticed that while in comments and in default values for variables in ini file `enemy_race` and `enemy_race_#` word Random used starting from capital letter in lowercase but in code all the checks done against all-uppercase RANDOM (or RANDOMTP etc.) without any trace of case insensitive comparison.

So I'm wondering should it be case-insensitive or should just .ini file be fixed?

**Comment by heinermann** [comment]
It should be case insensitive. I think the string is uppercased rather than
compared case insensitively. You should be able to get away with a cleaner
`race = BWAPI::Race(rand()%3);` since the race values are fixed.

**Comment by heinermann** [comment]
So basically, just compare against uppercase. The reason the string is uppercased instead of not compared case insensitively is because it looks cleaner in the code.

If you want to make your changes and open a pull request that would be great, because #563 will make major changes to the auto menu code.

**Comment by Predelnik** [comment]
1. It seems to me there is no general function for making string uppercase in the code, I've found a couple of places where std::transform with ::tolower used on string copy but it seems like in this case it would be used in too many cases (looks like string like SINGLE_PLAYER, BATTLE_NET, ON/OFF switches should be checke like that too). So there's probably a need to create some utitlity function to make string uppercase (with copying it). If you agree with that I would like to know in which header it should be placed, it's sadly not very obvious to me :(

2. Another strange little thing I noticed not very important of course, that if you write into auto_menu  something which differs from it's standard values (including OFF) the behavior will be a bit strange, that should probably be fixed and it should act as if it's off.

3. I don't mind doing pull request but if you can fix some things yourself (for example because of my lack of knowledge about the project structure I mentioned in the first item) during refactoring I don't mind waiting for it and reapplying my changes because they're not so significant in anyway )

**Comment by heinermann** [comment]
1. You're right. Try `Util/Convenience.h`.
2. Sounds good. Maybe we can add a BWAPI AutoMenuType internally which acts as a BWAPI Type. Possibly in another issue.
3. OK I'll work on some of the things then.
