### ISSUE TITLE
onUnitComplete somtimes wrongly called on unit creation

### ISSUE THREAD

**Issue by ufsqufbqifbqibfuiq** [bwapi/bwapi#562]
I don't know if it is the right place to post this.

In GameImpl::computePrimaryUnitSets(),
the "completed" attribute is tested with a call to isCompleted().
But isCompleted() check the UnitImpl::isCompleted member that is not up-to-date.
This is because UnitImpl::isCompleted is updated by updateData(), called by extractUnitData(), that is called *after* computePrimaryUnitSets().

However, there is a _isCompleted member that is updated by computeUnitExistence().
computeUnitExistence() is called *before* computePrimaryUnitSets() so a possible solution is to replace [line 479 in GameUnits.cpp] 
    if ( !u->wasCompleted && u->isCompleted() )
by 
    if (!u->wasCompleted && u->_isCompleted)

I tested it and it got onUnitComplete to work.
I'm a github newbie so I don't if I should and know how to upload the file with the proposed solution.

**Comment by heinermann** [comment]
This was fixed in 499aefbf . See #553 . The fix will be in BWAPI 4.1.1.
