### ISSUE TITLE
Some issues regarding isUnderAttack()

### ISSUE THREAD

**Issue by Predelnik** [bwapi/bwapi#565]
So initially I ran into some problems while using `isUnderAttack` with no-gui and maximum speed. My problem was that apparently `self->recentlyAttacked` was stuck as `true` on some building for a long time / indefinetily.
So I've done some testing by adding following line to `UnitDebug` for each unit:

    Broodwar->drawTextMap (u->getPosition(), std::to_string (raw->lastEventTimer).c_str ());

My observation is that it looks like number of frames for lastEventTimer to pass depends on game speed, so for example for speed 500 it takes around 7 frames, and for speed 1000 around 4. It looks like what it means is that for  fast game speeds unit reported as under attack for much longer amount of frames than for slower. Though I don't know if it's really getting stuck on very high speeds, that's need to be investigated. 

I think the fact that it's speed-dependent alone is very grieving since the bot behavior may significantly change depending on game speed.

Not sure about any workarounds but in current state of things looks like more solid approach is to check if any enemy units are attacking and what they attack.

**Comment by heinermann** [comment]
Yes this is probably true since it is a UI specific value.

**Comment by heinermann** [comment]
See #549 for more information.

**Comment by heinermann** [comment]
I'm going to track this in #549. Fixing that will also fix your issue. :)
