### ISSUE TITLE
UnitFinder fails for IDs > 1700 in BWAPI Client

### ISSUE THREAD

**Issue by ufsqufbqifbqibfuiq** [bwapi/bwapi#571]
I've got some crashes (read "security failure") in BWAPI::Templates::iterateUnitFinder.

The CRT reports that "A buffer overrun has occurred in AIModuleLoader.exe which has corrupted the program's internal state". 

It is due to the stack security cookie being overwriten during the execution of BWAPI::Templates::iterateUnitFinder. Just before the function return, __security_check_cookie is called and it raises this error.

It occurs when the game has run for a long time, with a lot of units created (currently my bot only know how to spam marines), and playing vs 2 zerg computers.

By setting a memory write breakpoint on the cookie, I've caught the following:

    //dwFinderFlags[iUnitIndex] = 0; BWAPIClient\Source\GameImpl.cpp, line 148
    mov         dword ptr [esp+ebx*4+50h],0              // ebx = 1703

dwFinderFlags is a stack array of 1701 elements allocated by BWAPI::Templates::iterateUnitFinder.

I though that BWAPI assumed that units ID can never be > 1700, but it seems that here iUnitIndex is equal to 1703, erasing the cookie.

What is going on ?

Edit:

From the post game screen, the computers created 508 + 309 units, and my bot 747.
This is a total of 1564 units created, not far from 1700...

**Comment by ufsqufbqifbqibfuiq** [comment]
Dear me,

I got some other crashes, so I looked further, and it seems that this issue will eventually happend for unit-heavy games.

Here is how unit IDs are created:

    int Server::getUnitID(Unit unit)
    {
        if ( !unit )
            return -1;
        if (unitLookup.find(unit) == unitLookup.end())
        {
            unitLookup[unit] = (int)(unitVector.size());
            unitVector.push_back(unit);
        }
        return unitLookup[unit];
    }

Now I don't know what `unitLookup[unit] = (int)(unitVector.size());` does for an unordered_map (well... I never used an unordered_map), but the returnd ID is unitVector.size().

So I looked at BWAPI::BroodwarImpl.server.unitVector in starcraft.exe process, and it has a size of 1706 at the instant of the crash.

I also have (BWAPI::BroodwarImpl).unitArray[1625].id equal to 1704.

Is this a bug, or a known limitation of BWAPI ?
Why isn't there any check in Server::getUnitID to assert that the returned ID is < 1700 ?
Aren't IDs supposed to be reused when the unit is dead ?

Thank you in advance!

**Comment by heinermann** [comment]
Definitely a bug, since ID is always expected to be less than 1700. I'm not sure why that array is size 1701 when it should be size 1700.
Added the assert but I don't think it will help much since we still need to figure out why it's getting ids >= 1700.

I actually don't know what is happening or why, I've never seen this as an issue before. The client is really messed up. The idea that this is inconsistent means that the logic behind all of this is wrong. I don't have a test case to repro it so I'm not sure how to go about it.

**Comment by ufsqufbqifbqibfuiq** [comment]
Thanks for your answer.

A simple workaround would be to increase all units array[1700] to... i don’t know, maybe 5000 is definitely enough, as 1700 was almost never a problem before. 

The memory usage would probably still be ok, for “nowaday” computers.

As a repro, I could send you the replays. I also have full dumps of starcraft.exe and moduleLoader.exe (few hundreds Mo though).
Or I could send you my bot dll so you could let it play. On maps like Luna the final it happens 25% of the games, that is when my bot don’t die.

**Comment by heinermann** [comment]
If the programmer wanted to, they could just access `data->unitArray` like in the BWAPI Client and get the actual unit index.

So I don't see the point of remapping the IDs. I'm actually not sure why we do?

**Comment by heinermann** [comment]
So I think I'm going to remove the remapping code here because it just seems pointless. I'll create a test case and we'll see how it goes.

**Comment by heinermann** [comment]
I decided to use safety strats and just use an unordered_map instead so that all of the current logic remains the same.

Also this bug only happened in the client.
