### ISSUE TITLE
There is a timespan where overlord exists but doesn't provide supply

### ISSUE THREAD

**Issue by Darker** [bwapi/bwapi#573]
Not sure if this is a bug in BWAPI, but it's definitelly an issue. When the overlord spawns, for a short moment (maybe just one logic frame) it's already unit type `Zerg_Overlord`, but the global info about supplies provided returns lower values as if the overlord didn't exist.

Simple time-invariant AI will try to build second overlord at that moment. The only solid workaroud I see there is to calculate supplies manually from units when deciding to spawn overlords.

**Comment by heinermann** [comment]
This seems like a Starcraft thing. Is it in the player's completed unit count?

**Comment by fishbullet** [comment]
same thing here. I use [BWMirror](https://github.com/vjurenka/BWMirror) and `incompleteUnitCount(UnitType unit)` return 0 while overlord morphing, only when overlord morph complete it's return `-1` and after again skip to 0.

**Comment by ratiotile** [comment]
I noticed this a while back on v3.7.4 - there is one frame between the egg dying and the Overlord spawning it seems where it provides no supply and there is no Overlord nor egg morphing Overlord for a frame.

**Comment by fishbullet** [comment]
@ratiotile how you handle this case?

**Comment by ratiotile** [comment]
@fishbullet  I had higher level abstractions to take care of supply. There was a BuildOrderManager that remembered the queued up units, which listened to the OnUnitCreate event and checked that the unit had been created before popping from the queue. SupplyManager had getSupply() for current supply and getPlannedSupply() which included queued up units.

**Comment by Darker** [comment]
@ratiotile  Yes, I made similar manager but that alone didn't solve the issue. After the overlord appeared, manager popped it out of the queue but then added another as the supply was still 9/9.

Only adding the `getSupply` just as you did and looping through existing units to calculate the real value worked to me. Actually the only difference is that I called the other method `getPromisedSupply` :)

**Comment by ratiotile** [comment]
It might be an issue within bwapi then, or the game itself. I seem to remember that the supply counter in-game didn't update immediately when overlords popped either so maybe the starcraft engine updates it a frame later.

@Darker To clarify, I popped it from the buildorder queue, but added it to a list of supply providers, and iterated through that to tally up the supply provided.

**Comment by Jluil** [comment]
do you use Broodwar->setLatCom(false)?

**Comment by ratiotile** [comment]
no, does it make a difference?

**Comment by Jluil** [comment]
Well LatCom introduces a lot of buggy behaviors such as you described.
I strongly recommend to turn it off as I don't seem to experience this issue.
