### ISSUE TITLE
[LibReplayToolTest] Fix Visual Studio Express compatibility with libraries

### ISSUE THREAD

**Issue by DanSibbernsen** [bwapi/bwapi#589]
The LibReplayToolTest is dependent on libgmockDX86_msvc10.lib which is not compatible with visual studio 2013. Can we update this library so we can fix this portion of the build?

Thanks.

**Comment by heinermann** [comment]
You can safely unload that project. I've never had the libgmock libraries available to me, and I've never used the libReplay tool. I don't know if anyone does. If anything I would rather take it out of the BWAPI solution file or even the repository and put it somewhere else.

**Comment by heinermann** [comment]
As of 5dc8d602da0290c4c85ea10ddf4c39a97d4b8b8c, BWAPI is no longer maintaining the Replay_Tool.
