### ISSUE TITLE
Cant build succesfully with vs2013

### ISSUE THREAD

**Issue by bagazi** [bwapi/bwapi#591]
I Cant build succesfully in vs2013， with this problem   
=============================================================
error C1001: An internal error has occurred in the compiler.	F:\Source\Topic\BWApi2\bwapi\bwapi\BWAPI\Source\BWAPI\RegionImpl.h	34	1	BWAPI
=============================================================
which is point to     RegionData  data = {};  

Should I set the vs2013 manully？  Please help me out

**Comment by heinermann** [comment]
Are you using the latest version of VS 2013?

**Comment by bagazi** [comment]
Oh,let me  check out, by the way,what is the correct version?Or could I directly update in vs2013?

**Comment by heinermann** [comment]
You can update within Visual Studio.

**Comment by bagazi** [comment]
Oh yeah,under your advise，I solve this problem。Thanks you very much.Cause I am a fresh man In BWapi,Could I get some guidance ？ I am eager to learn the ai module of this project,which is very important for me

**Comment by bagazi** [comment]
How can I  know  structure of BWAPI well ？ Which is frameWork，which is App ？And what can I do ?Please Please illuminate me .

**Comment by bagazi** [comment]
How can I  know  structure of BWAPI well ？ Which is frameWork，which is App ？And what can I do ?Please Please illuminate me .

**Comment by bagazi** [comment]
I run the project of ExampleAIClient   at the point of " this->gameTableFileHandle = OpenFileMappingA(FILE_MAP_WRITE | FILE_MAP_READ, FALSE, "Local\\bwapi_shared_memory_game_list" );

in client.cpp Ln 37  get the map is none .what is the problem?

**Comment by heinermann** [comment]
Try running it as an administrator.

**Comment by heinermann** [comment]
Since the original issue was solved, I am closing this ticket.
