### ISSUE TITLE
Consider bringing BWTA back to BWAPI

### ISSUE THREAD

**Issue by heinermann** [bwapi/bwapi#593]
[BWTA2](https://bitbucket.org/auriarte/bwta2) is under active development and updated for use with BWAPI 4.1.x.

Things I would like to see:
- [ ] Not having to copy DLLs to the Windows directory.
- [ ] Fixed stability issues.
- [ ] Faster algorithms.

**Comment by heinermann** [comment]
That's for release-only inclusion and not the source.

**Comment by krasi0** [comment]
Faster algorithms especially for ground distance calculations is something many AI developers would benefit from

**Comment by albertouri** [comment]
In BWTA2 there is already a faster algorithm for ground distances (details in [Release Notes](https://bitbucket.org/auriarte/bwta2/wiki/Release%20Notes) BWTA 2.0 changes). I didn't make a "big" announcement because I would like to test it better and I'm working on a faster algorithm ;)

**Comment by N00byEdge** [comment]
Still relevant?

**Comment by krasi0** [comment]
No, I don't think so
