### ISSUE TITLE
Be able to enable CompleteMapInformation only for the tournament module

### ISSUE THREAD

**Issue by albertouri** [bwapi/bwapi#594]
It would be great if the tournament module can access to the full information while the bots cannot.

**Comment by heinermann** [comment]
Might be tricky, since complete map information is a flag that affects a lot of data. The reason it can only be enabled in the onStart callback is because of the effects it would cause in later frames. We would need to design a better system to manage BW data.

**Comment by N00byEdge** [comment]
Closing for now as BWAPI is not built in a way this would be possible.

**Comment by heinermann** [comment]
Well it may be possible, but probably not in Remastered, since there's no plan to have a complete map info flag there.
