### ISSUE TITLE
Make BWAPI compatible with Teippi

### ISSUE THREAD

**Issue by heinermann** [bwapi/bwapi#609]
There is a new limit removing hack that may not work with BWAPI: https://github.com/neivv/teippi
Relevant thread: http://www.staredit.net/topic/16823/
- [ ] Check for Teippi event on game start
- [ ] Conditionally use enhanced selection command
- [ ] Conditionally use enhanced right click command
- [ ] Conditionally use enhanced target order command
- [ ] Conditionally use different unit IDs (instead of BW array).
- [ ] Remove any reliance on BW Bullet array.
- [ ] Build new unit finder index every frame. Consider leveraging Teippi's unit finder.
- [ ] Export BWAPI callbacks as DLL functions that other hacks can access.
- [ ] Find alternative frame progression hook
- [ ] Find alternative method of obtaining refunded resources.
- [ ] Conditionally use Teippi's extended Unit structure.
  - [ ] Lookup ID
  - [ ] Loaded units
  - [ ] Kills

**Comment by heinermann** [comment]
BWAPI's offsets and hooking mechanisms:

- BWAPI offsets: https://github.com/bwapi/bwapi/blob/master/bwapi/BWAPI/Source/BW/Offsets.h#L39-L280
- BWAPI hooking/patching: https://github.com/bwapi/bwapi/blob/master/bwapi/BWAPI/Source/CodePatch.cpp#L18

**Comment by neivv** [comment]
How would the situations where both hacks hook the same code be handled? 
Teippi generally writes a jump to the first instruction of function and reimplements the entire function.

What about cases where Teippi leaves a Starcraft array unused and BWAPI assumes it contains something?
unitFinder gets completely replaced by another implementation. Should some kind of API to be provided to Teippi's implementation?
Alternatively calling the bw functions 004308A0 ("FindUnitsRect") and 004E8320 ("FindNearestUnit") could be used as a makeshift API, as Teippi hooks them and the hooks behave as the bw ones do.

**Comment by heinermann** [comment]
That is a very good point. Your hack does some pretty aggressive hooking. I'm not sure at all what to do in this case. I've made changes to BWAPI to maintain compatibility with w-mode and resolution expander before, but this is by far the largest. I'll be making some tests later today to see how much needs to be changed.


Regarding the unit finder, I think this one's on us to reimplement, since its use is strictly to search units within BWAPI via getUnitsInRectangle API. We iterate every unit every frame anyway to synchronize the API with Broodwar and decide what bots have access to, and we actually build a second finder table for client (pipes+shared memory interface) modules from the original.

I'm more concerned about access to units. Is there an explicit way to check if Teippi is injected? BWAPI creates an event that can be checked. I'll toss that info in a wiki in a bit. BWAPI has non critical functionality to convert IDs to units, and critical functionality to convert units to IDs (we write the commands directly into the command buffer).

Do you know how performant it is to have 65000 units in a game? Because if it can be limited, going back to the 16-bit ID would be significantly more compatible, and then BWAPI could just change the way it parses IDs if Teppei is detected. But we can still conditionally change the way commands are sent anyway. The most important part here is just being able to obtain the unit ID.

**Comment by heinermann** [comment]
So initial testing shows that BWAPI is completely non-functional. The menu speed hack works, and windowed mode hotkey works, but doesn't show anything.

![screenshot from 2015-08-30 14 29 38](https://cloud.githubusercontent.com/assets/1966366/9569564/111fef9e-4f24-11e5-9ca6-64c879c7ba16.png)

![screenshot from 2015-08-30 14 30 11](https://cloud.githubusercontent.com/assets/1966366/9569565/14608ace-4f24-11e5-9981-ed158c0aede6.png)

**Comment by neivv** [comment]
I posted a list of things that i feel would have to be in IRC, but I'll copy it here:

    // THESE BREAK
      // Commands using unique unit ids break
      const u32 BWFXN_QueueCommand = 0x00485BD0;
 
      // Arrays, won't work
      std::array<CUnit, UNIT_ARRAY_MAX_LENGTH> IS_REF(UnitNodeTable, 0x0059CCA8);
      std::array<CBullet, BULLET_ARRAY_MAX_LENGTH> IS_REF(BulletNodeTable, 0x0064B2E8);
 
      // unit_search
      std::array<unitFinder, UNIT_ARRAY_MAX_LENGTH * 2> IS_REF(UnitOrderingX, 0x0066FF78);
      std::array<unitFinder, UNIT_ARRAY_MAX_LENGTH * 2> IS_REF(UnitOrderingY, 0x006769B8);
 
      // unit_search->Size()
      int IS_REF(UnitOrderingCount, 0x0066FF74);
 
    // Might break Teippi's debugging console & draw hooks
    // Not a huge deal
    extern void (__stdcall *pOldDrawGameProc)(BW::Bitmap *pSurface, BW::bounds *pBounds);
    extern void (__stdcall *pOldDrawDialogProc)(BW::Bitmap *pSurface, BW::bounds *pBounds);
 
    // game.cpp ProgressFrame? could use isGamePaused?
    static const u32 BWFXN_P_IsGamePaused           = 0x004D974E;
 
    // Unit::CancelZergBuilding
    static const u32 BWFXN_RefundMin3                     = 0x0045D44D;//morphing
    static const u32 BWFXN_RefundMin3ReturnAddress        = 0x0045D454;//morphing
    static const u32 BWFXN_RefundGas3                     = 0x0045D46e;//morphing
    static const u32 BWFXN_RefundGas3ReturnAddress        = 0x0045D474;//morphing
 
    // game.cpp/triggers.cpp
    static void (__stdcall * const BWFXN_ExecuteGameTriggers)(DWORD dwMillisecondsPerFrame) =  (void(__stdcall*)(DWORD))0x0048A460;
    static const u32 BWFXN_ExecuteGameTrigsCallPatch = 0x004D9798;
 
    // DIFFERENT DATA LAYOUT
    CUnit::loadedUnitIndex is replaced by single-linked list Unit::first_loaded and Unit::next_loaded
    Unit's kills are moved to 32-bit variable at different location
    Most of the .grps are stored in memory as decoded, but not all.
        Detecting their format is messy and full of type casts.
        But BWAPI doesn't read them?
 
    // NO ISSUE AS LONG AS THE SELECTION LIMIT IS NOT TOUCHED
      std::array<CUnit*, MAX_SELECTION_COUNT> IS_REF(ClientSelectionGroup, 0x00597208);
      u8 IS_REF(ClientSelectionCount, 0x0059723D);

The windowed mode not working is likely caused by Teippi's draw hooks that can be disabled, but there is freeze logging code that uses screen draws to determine if the game was frozen. It should be trivial to modify so it does not need to hook entire drawing system

**Comment by heinermann** [comment]
~~~
  // Commands using unique unit ids break
  const u32 BWFXN_QueueCommand = 0x00485BD0;
~~~
The solution would be to just detect if Teippi is injected (OpenEvent??) and use the 32-bit IDs instead.

~~~
  // Arrays, won't work
  std::array<CUnit, UNIT_ARRAY_MAX_LENGTH> IS_REF(UnitNodeTable, 0x0059CCA8);
  std::array<CBullet, BULLET_ARRAY_MAX_LENGTH> IS_REF(BulletNodeTable, 0x0064B2E8);
~~~
We can trivially create our own id -> unit mapping. So we would remove our direct access logic and instead create an unordered_map to track ID -> Units. It would be populated when we iterate the units (where we would check for the existence of Teippi).

~~~
  // unit_search
  std::array<unitFinder, UNIT_ARRAY_MAX_LENGTH * 2> IS_REF(UnitOrderingX, 0x0066FF78);
  std::array<unitFinder, UNIT_ARRAY_MAX_LENGTH * 2> IS_REF(UnitOrderingY, 0x006769B8);

  // unit_search->Size()
  int IS_REF(UnitOrderingCount, 0x0066FF74);
~~~
Solution is to build our own array when we iterate units, so then we can remove all three of these references. I think being more independent of the chaos happening in BW is a good thing.

~~~
// Might break Teippi's debugging console & draw hooks
// Not a huge deal
extern void (__stdcall *pOldDrawGameProc)(BW::Bitmap *pSurface, BW::bounds *pBounds);
extern void (__stdcall *pOldDrawDialogProc)(BW::Bitmap *pSurface, BW::bounds *pBounds);
~~~
Unlikely. I don't think Teippi modifies this. These are just the old values taken from `draw_layers = 0x006CEF50;`. A common pattern in BWAPI hooks is that the previous function pointer is stored, even if it is sometimes trivial (i.e. Storm hooks). This pattern improves compatibility with other hacks.

~~~
// game.cpp ProgressFrame? could use isGamePaused?
static const u32 BWFXN_P_IsGamePaused           = 0x004D974E;
~~~
Yes, BWAPI uses this to hook frame progression. This would otherwise be the IsPaused() call in your ProgressFrame function. This hook is a blocker for BWAPI to function at all. BWAPI really doesn't do anything without this.

Looking at ProgressTurns (BW managed), there doesn't appear to be a good hooking point. We could potentially hook GetTickCount and do a stack frame analysis to determine where we are (i.e. ProgressTurns). Otherwise we would hook deeper in the game loop and potentially lose some control (i.e. paused game won't call our hook) or encounter new errors in the assumptions made at the before-logic hook. An alternative could be to export a DLL function and let Teippi call it (checking for BWAPI's [event handler](https://github.com/bwapi/bwapi/blob/1e6f11f40872d29ac33032b86c751c821966ac9d/bwapi/BWAPI/Source/DLLMain.cpp#L220-L226)).

~~~
// Unit::CancelZergBuilding
static const u32 BWFXN_RefundMin3                     = 0x0045D44D;//morphing
static const u32 BWFXN_RefundMin3ReturnAddress        = 0x0045D454;//morphing
static const u32 BWFXN_RefundGas3                     = 0x0045D46e;//morphing
static const u32 BWFXN_RefundGas3ReturnAddress        = 0x0045D474;//morphing
~~~
Not a big deal. Only corresponds to [BWAPI::PlayerInterface::refundedMinerals](http://bwapi.github.io/class_b_w_a_p_i_1_1_player_interface.html#a081936a2f743365157394f7e4d980ce7) and its sister function. Most people don't use this, and it will have little impact on AIs that do.

~~~
// game.cpp/triggers.cpp
static void (__stdcall * const BWFXN_ExecuteGameTriggers)(DWORD dwMillisecondsPerFrame) =  (void(__stdcall*)(DWORD))0x0048A460;
static const u32 BWFXN_ExecuteGameTrigsCallPatch = 0x004D9798;
~~~
It looks like Teippi already does what we want to do, which is a trigger progression bug fix for when game speeds are modified. So this doesn't matter.

~~~
// DIFFERENT DATA LAYOUT
CUnit::loadedUnitIndex is replaced by single-linked list Unit::first_loaded and Unit::next_loaded
Unit's kills are moved to 32-bit variable at different location
~~~
We would check for the existence of Teippi and likely cast the Unit structure to the extended structure in this case.

~~~
Most of the .grps are stored in memory as decoded, but not all.
    Detecting their format is messy and full of type casts.
    But BWAPI doesn't read them?
~~~
I don't think we are touching GRPs right now.

**Comment by neivv** [comment]
So, as BWAPI can get the lookup_id from unit pointer, it will be enough from it as it constructs its own unit->id and id->unit mappings?

I'll add CreateEvent call similarly how BWAPI does it with name `Teippi #%d`, where `%d` is the pid.
Having the event created as the game has been patched should be fine and BWAPI can detect it from there?

Hooking ProgressTurns may work if BWAPI keeps track of Starcraft's frame counter and only considers frame to be progressed when the counter has changed from its previous value. 

But I would not oppose adding BWAPI detection and calling a function it provides to Teippi either. If that is added, how would Teippi receive the function? Is it ok to just LoadLibrary/GetProcAddress as that breaks if the bwapi's .dll is renamed for some reason. And can Teippi assume that the BWAPI's event is already created when it applies its code patches or does it need to check for it at a later point?

If the refund hook is not important, that's good as it seemed to be the hardest one to get compatible.

**Comment by heinermann** [comment]
The modules can be injected in any order, and BWAPI can be injected at any time. BWAPI will function even if injected during a match, though not completely correctly since we use our own frame counter. I recommend checking for BWAPI on match start, as it will be fully functional if injected at any other time.

BWAPI's module name is BWAPI.dll or BWAPId.dll by default. It's possible under uncommon circumstances that it could change(user renames and injects it directly), in which case you would iterate all loaded modules, looking for the function signature (and storing the pointer to it when found). You would only check for it once if the event exists though, so the control flow is not too bad.

**Comment by heinermann** [comment]
I'll be checking for Teippi in that same way, sometime where it's guaranteed to be injected, but before we actually handle IDs.

I may throw some code snippets up as well.


There's another incompatibility as well, which may involve the detours to some Storm functions. We may have to apply the detours to Teippi if it's detected. This should fix the windowed mode/drawing stuff, since IIRC I saw a call which the windowed mode relies on.

**Comment by heinermann** [comment]
Actually scratch that, since Teippi doesn't import the Storm library from an import table.

**Comment by neivv** [comment]
Alright, Teippi now plays nicer with the draw hooks and the windowed mode works:
![teip bwapi](https://cloud.githubusercontent.com/assets/9514159/9604647/8d151766-50c1-11e5-96c1-44c81338c69a.png)

BWAPI did not draw anything, but it may just have been as it didn't consider game to be started.
Also I feel like there should be option to disable Teippi's draw system completely, as it is quite slow.
That is a bit more work though.

The commands using unit ids have slightly different format in addition to the 32-bit ids. I don't think there was any real reason for it, so it can be changed to be closer to bw (or just cleaner) if needed.

    Selection commands:
      u8 id (0x9, 0xa, 0xb) @ 0x0
      u8 zero @ 0x1
      u32 lookup id count @ 0x2
      u32 lookup ids[] @ 0x6

    Right click / Targeted order:
      u8 id (0x14, 0x15) @ 0x0
      u16 position[2] @ 0x1
      If flag 0x80: (Ground)
        u32 unused @ 0x5
      Else if flag 0x40: (Fog of war unit)
        u16 fow unit id @ 0x5
        u16 unused @ 0x7
      Else: (Unit)
        u32 lookup id @ 0x5
      u8 flags @ 0x9 (Queued if flag 0x1)
      If targeted order:
        u8 order @ 0xa
      
      (Right click command has length of 10 bytes, targeted order 11)

**Comment by heinermann** [comment]
Thanks, will implement them when I get the time. Potentially the coming weekend. Also I think your unit flags and some unit structure stuff is more well defined than BWAPI's. Additionally, BWAPI has some stuff in its current unit structure that Teippi is missing.

**Comment by heinermann** [comment]
Sorry, will no longer be pursuing this due to time constraints and now newer versions which will eventually make a compatibility layer unnecessary.
