### ISSUE TITLE
Why not on StarCraft 2？

### ISSUE THREAD

**Issue by bagazi** [bwapi/bwapi#610]
2 seems more attractive and popular，so why not play on StarCraft 2？

**Comment by heinermann** [comment]
Primarily for three reasons:
1. I'm the only active developer for BWAPI. It has taken **years** to get to this point. I just started my first full time job, which now means I have even less time to work on it. I'm not interested in developing something like this for StarCraft 2.
2. SC2 is still actively being developed and used. Blizzard Entertainment will be very strict about hacks involving it, and may try to shut down any large scale API project. Right now, Blizzard Entertainment has shown that they indirectly support BWAPI's contribution to [academics](https://github.com/bwapi/bwapi/wiki/Academics), providing prizes to some of the AI vs AI tournaments.
3. In the interest of academic development, Broodwar is cheaper, and its hardware requirements are lower, making it more accessible to university students. BWAPI is actively being used as university courseware (professors are actually using BWAPI in classrooms), so I think maintaining BWAPI is a higher priority.

If you want a SC2 API, this is not the place to make such a request. Meanwhile you could check out [this project](https://graphics.stanford.edu/~mdfisher/GameAIs.html) and see if it has any relevance.

For additional information, see this [FAQ](https://github.com/bwapi/bwapi/wiki/FAQ#will-there-be-an-api-like-this-for-starcraft-ii-faq-sc2).
