### ISSUE TITLE
Installer does not work properly when Starcraft's registry keys are missing

### ISSUE THREAD

**Issue by neivv** [bwapi/bwapi#611]
As brought up on IRC:
If the installer cannot find starcraft's installation, it prompts for the directory, which can be given to proceed in installation.
However, when starting to copy files it will annoyingly prompt again for the directory dozens of times (once for each file?)

Seems that the installer script does not write the registry key properly.

**Comment by heinermann** [comment]
The installer was checking `software/WOW6432Node` or something, and then writing to `software/WOW6432Node/WOW6432Node/`. Seems to handle the `WOW6432Node` automatically now.
