### ISSUE TITLE
[Critical]Cannot upgrade pneu. carapace, ventral sacs.. from Hive

### ISSUE THREAD

**Issue by Jluil** [bwapi/bwapi#612]
While these can be upgraded from Lair it is not possible once you upgrade to Hive.
Tested on pneu. carapace and ventral sacs.
Need to also check antenae and burrow.

**Comment by heinermann** [comment]
Which version of BWAPI?

**Comment by Jluil** [comment]
4.1.2

**Comment by heinermann** [comment]
Also occurs for burrow.

**Comment by heinermann** [comment]
This would also impact the Spire -> Greater Spire upgrades as well.
