### ISSUE TITLE
Zerg_Egg training queue empty sometimes

### ISSUE THREAD

**Issue by davechurchill** [bwapi/bwapi#613]
Adam Heinermann: I ran into a strange situation today where I had a Zerg Egg with a getTrainingQueue() that returned size 0. I used this code in my module's onFrame() function:

``` c++
    for (BWAPI::UnitInterface * unit : BWAPI::Broodwar->self()->getUnits())
    {
        if (unit->getType() == BWAPI::UnitTypes::Zerg_Egg)
        {
            auto & queue = unit->getTrainingQueue();

            if (queue.size() > 0)
            {

            }
            else
            {
                BWAPI::Broodwar->printf("Warning: Empty training queue on a zerg egg");
            }

            continue;
        }
    }
```

The vast majority of the time you create something with a larvae this doesn't get triggered, but on very rare occasions it does. And to me it seems like an egg should never have a queue of size 0. Do you know under what conditions this is triggered? Right now to me it appears to be unexplained.

**Comment by heinermann** [comment]
See http://pastebin.com/97kqxwKg for style.

I don't know under which conditions it gets triggered. I would need to dig deep.

Does it trigger more or less for some specific unit types?
Does latency compensation have an impact?

This sounds like an issue that I'd want actual unit tests for.

**Comment by davechurchill** [comment]
I don't think I can answer any of those questions with any certainty.

For now I've switch to simply calling eggUnit->getBuildType() instead of going through the training queue method, and this works perfectly

**Comment by heinermann** [comment]
This is with latency compensation enabled right? According to #783 this is fixed but please reopen if that's not the case.

**Comment by davechurchill** [comment]
I have no idea - was almost 3 years ago

**Comment by N00byEdge** [comment]
Doesn't mean it's not worth fixing ;)

**Comment by davechurchill** [comment]
I just meant I wasnt sure if latency compensation was on
