### ISSUE TITLE
Request: Function to get the unit which a given unit is currently training

### ISSUE THREAD

**Issue by davechurchill** [bwapi/bwapi#619]
Example: A function which returns the SCV that a command center is currently training.

Notes: It seems that the frame after you give a build command to a command center getRemainingTrainTime() > 0 but there is no SCV unit yet on the map. For this frame, its training queue is of size 1 and the value of it is the SCV.

**Comment by heinermann** [comment]
Seems like Unit::getBuildUnit does this. I will need to update its documentation.

The frame after giving the command probably adds it to the queue but doesn't actually create the unit yet until the next frame.
