### ISSUE TITLE
getRemainingTrainTime() bug?

### ISSUE THREAD

**Issue by davechurchill** [bwapi/bwapi#620]
In single player with BWAPI::Broodwar->getLatencyFrames() having a value of 2.

Issue a command center a command to train an scv on frame N
Check on that same frame N the CC's getRemainingTrainTime, it's > 0, however the unit that the building is constructing hasn't appeared yet. The unit appears N + latency frames later.

Shouldn't getRemainingTrainTime return 0 during the 2 latency frames between issuing the command and the actual unit starting training in the game?

**Comment by heinermann** [comment]
Is latency compensation enabled?

**Comment by davechurchill** [comment]
No idea... if it wasn't on by default then probably not?

**Comment by heinermann** [comment]
I think it's on by default.

**Comment by N00byEdge** [comment]
This is a non-issue. It's latcom preparing you for the fact that a unit will appear there in a few frames.
