### ISSUE TITLE
Naming Inconsistency?

### ISSUE THREAD

**Issue by davechurchill** [bwapi/bwapi#621]
Everywhere in BWAPI the main building of a race is called a resource depot, ie: UnitType.isResourceDepot(), except in the Race class where it's Race.getCenter() which seems odd. Perhaps change it to Race.getResourceDepot()?

**Comment by heinermann** [comment]
The obligatory renaming something every minor version. Perfect. I couldn't think of what I was going to rename for next version. =)

**Comment by davechurchill** [comment]
Haha, amazing :) Glad I can keep up the tradition

**Comment by heinermann** [comment]
Pushing it up to 4.1.3 since this is a type class and doesn't affect compatibility with bots compiled with older versions.

**Comment by heinermann** [comment]
Decided to create a new policy regarding renaming things, since people were upset in the past.

https://github.com/bwapi/bwapi/blob/develop/CONTRIBUTING.md#renaming-a-function
