### ISSUE TITLE
Make SNP_DirectIP more robust

### ISSUE THREAD

**Issue by heinermann** [bwapi/bwapi#625]
- [x] every function at spiFunctions returns a true/false bool (which gets compiled into a 0x01/0x00 char), the game expects a non-zero/zero int
- [ ] spiInitialize needs to call UISelectHero (bnCallbacks[19]) (TODO: Investigate)
- [x] spiUnlockDeviceList should have 1 argument, not 0. (TODO: Investigate)
- [ ] thrown GeneralException's at bind & sendPacket functions are not handled properly and crashes the game (TODO: Investigate)

**Comment by xboi209** [comment]
What is the purpose of reducing the number of functions?

**Comment by heinermann** [comment]
Yeah good point. It's a non-issue.

**Comment by xboi209** [comment]
For the spiFunctions, are the non-zero values always 1?

**Comment by heinermann** [comment]
Yes, typically. I'm pretty sure it's using the TRUE/FALSE defines from the windows header.

**Comment by heinermann** [comment]
Closing this as the module is obsolete in newer versions, and the remaining tasks are not important.
