### ISSUE TITLE
Proposal: Build location retrieval

### ISSUE THREAD

**Issue by heinermann** [bwapi/bwapi#633]
Right now users are left to come up with their own build location logic. It would be cool to have a generic way to provide a system with a bunch of rules and then have it spit out build locations.

The requirements are as follows:
- Capable of choosing build locations as the internal built in AI does.
- Capable of choosing build locations as BWSAL does.
- Can receive modular rules for different unit types.

**Comment by N00byEdge** [comment]
Is this still something we should do?

**Comment by heinermann** [comment]
It's something I wanted to do but we can leave it as a separate library and remove the current partially reverse engineered implementation. Resolving.
