### ISSUE TITLE
Release zipped binaries alongside installer executable

### ISSUE THREAD

**Issue by heinermann** [bwapi/bwapi#637]
Some users have requested zip archives with only the compiled binary files.

**Comment by krasi0** [comment]
+1

**Comment by albertouri** [comment]
+1 If I already have a working bwapi/bot I want to update only BWAPI and not to "reinstall" it

**Comment by krasi0** [comment]
Exactly. Reinstalling overwrites BWAPI ini

**Comment by heinermann** [comment]
Latest build artifacts can be found [here](https://ci.appveyor.com/project/heinermann/bwapi/branch/develop/artifacts).

Future releases will include a 7z zipped version of the release folder.
