### ISSUE TITLE
Upgrade to VS2015

### ISSUE THREAD

**Issue by heinermann** [bwapi/bwapi#641]
Applicable Language Features:
- [x] - Inheriting constructors (Type classes, wrapper sets)
- [x] - constexpr (potentially no need to duplicate types as enumerations for switch cases, define global constants correctly, have better offset wrapping code)
- [x] - deprecated attribute (for renamed functions)
- [x] - Upgrade projects to VS 2015
- [x] - Upgrade example solution to VS 2015

**Comment by heinermann** [comment]
Application of `constexpr` is in progress.

Example:
~~~cpp
    switch (u->getType())
    {
    case int(UnitTypes::Zerg_Hive):
      Broodwar << "Found a Hive!" << std::endl;
      break;
    case UnitTypes::Terran_Command_Center.getID():
      Broodwar << "Found a Command Center!" << std::endl;
      break;
    }
~~~

**Comment by s7jones** [comment]
Is the develop branch using VS2015 yet?

**Comment by heinermann** [comment]
Yes it is.
