### ISSUE TITLE
Sometimes single units will stop doing anything, is it a problem with the filters?

### ISSUE THREAD

**Issue by s7jones** [bwapi/bwapi#646]
I'm writing a very simple 5 pooling Zerg, and I've noticed that sometimes my first (5/9 supply) drone will not respond at all. He doesn't go and get minerals.

I've pretty much followed the v4.1.2 ExampleAIModule code.

```cpp
	// Iterate through all the units that we own
	for (auto &u : Broodwar->self()->getUnits())
	{
		// Ignore the unit if it no longer exists
		// Make sure to include this block when handling any Unit pointer!
		if (!u->exists())
			continue;

		// Ignore the unit if it has one of the following status ailments
		if (u->isLockedDown() || u->isMaelstrommed() || u->isStasised())
			continue;

		// Ignore the unit if it is in one of the following states
		//if (u->isLoaded() || !u->isPowered() || u->isStuck())
		//	continue;

		if (u->isLoaded() || !u->isPowered())
			continue;

		if (u->isStuck())
			//Broodwar << "unit is stuck!" << std::endl;
			continue;

		// Ignore the unit if it is incomplete or busy constructing
		/* if ( !u->isCompleted() || u->isConstructing() )
		   continue;*/


		// Finally make the unit do some stuff!


		// If the unit is a worker unit
		if (u->getType().isWorker())
		{
			// if our worker is idle
			if (u->isIdle())
			{
				// Order workers carrying a resource to return them to the center,
				// otherwise find a mineral patch to harvest.
				if (u->isCarryingGas() || u->isCarryingMinerals())
				{
					u->returnCargo();
				}
				else if (!u->getPowerUp())  // The worker cannot harvest anything if it
				{                             // is carrying a powerup such as a flag
					// Harvest from the nearest mineral patch or gas refinery
					if (!u->gather(u->getClosestUnit(IsMineralField || IsRefinery)))
					{
						// If the call fails, then print the last error message
						Broodwar

 << Broodwar->getLastError() << std::endl;
					}

				} // closure: has no powerup
				else Broodwar << "is idle and has power up?" << std::endl;
			}
}
```

I can attach a replay ```Jade 1.0_ZvsU_073851.rep``` showing the behaviour.
[Jade 1.0_ZvsU_073851.zip](https://github.com/bwapi/bwapi/files/117060/Jade.1.0_ZvsU_073851.zip)

- I'm the blue Zerg in the bottom right.
- The first drones will harvert, and the Overlord scouts.
- Confusingly, and maybe a related issue - none of my drones make a Spawning Pool. They know to do this after the first drone has been created.

```cpp
if (u->getType().isResourceDepot()) {
	if ((Broodwar->self()->minerals() >= UnitTypes::Zerg_Drone.mineralPrice()) && (bo[indx] == UnitTypes::Zerg_Drone)) {
		if (!u->getLarva().empty()) {
			u->train(UnitTypes::Zerg_Drone);
			indx++;
		}
	}
}
```

```bo``` is a vector of <UnitType> e.g. ``` bo = { UnitType(UnitTypes::Enum::Zerg_Drone),
UnitType(UnitTypes::Enum::Zerg_Spawning_Pool),
UnitType(UnitTypes::Enum::Zerg_Drone), etc}```

--

Is it possible there is some problem with the Filters? Or could it be that calling u->train() on a Resource Depot is the problem?

Thanks.

**Comment by s7jones** [comment]
Could this be related to #566?

**Comment by heinermann** [comment]
No this is not #566 if it is consistent. I don't think I can make a conclusion without the full code. 

You can simplify it however with
~~~cpp
  if (u->getType() == bo[index].what builds()) {
      if (u->train(bo[index])) {
          index++;
      }
  }
~~~

But you still can't tell it to train a spawning pool because structures need build locations. In the future I plan to have default build locations, but you otherwise need to find a build location yourself for now.

Also you can just use UnitTypes::Zerg_Drone, etc. instead of constructing a UnitType from the enum.

**Comment by heinermann** [comment]
Closing, since there doesn't appear to be an issue. Please re-open if you think this was closed in error, thanks.
