### ISSUE TITLE
Sign file instead of hooking SFileAuthenticateArchive

### ISSUE THREAD

**Issue by xboi209** [bwapi/bwapi#651]
[StormLib](https://github.com/ladislav-zezula/StormLib) is able to sign files now. [Hooking SFileAuthenticateArchive](https://github.com/bwapi/bwapi/blob/master/bwapi/BWAPI/Source/CodePatch.cpp#L61) should no longer be necessary.

Example signing code: https://github.com/xboi209/MPQSigner/blob/master/src/main.cpp

**Comment by heinermann** [comment]
That's correct. I've signed the archive with Ladik's MPQ editor. We can remove the hook.
