### ISSUE TITLE
what the flag CompleteMapInformation is really about

### ISSUE THREAD

**Issue by mechaZYK** [bwapi/bwapi#653]
the flag CompleteMapInformation is about getting only the map information or about getting all information including the enemies?
this may influence the getMinerals() function, becaouse when expand, we need to know the value of the   minerals(the original information would be ok)

**Comment by heinermann** [comment]
[CompleteMapInformation](https://bwapi.github.io/namespace_b_w_a_p_i_1_1_flag.html#a394478b7ea50a1fea08f7a73bbad04aeaf6d5058525d1ce926407b5644594d790) is for all information, including enemy units.

You can get the original positions and values of minerals through [getStaticMinerals](https://bwapi.github.io/class_b_w_a_p_i_1_1_game.html#af4e7502ff1efddb5c1c9060dd46072e1) and [getResources](https://bwapi.github.io/class_b_w_a_p_i_1_1_unit_interface.html#aeaa12f38b628ab7b6ba14acf838df9bd).

**Comment by planckztd** [comment]
How to close CompleteMapInformation after I get the ground truth values, and continue game with only visiable information?  Wish your reply
