### ISSUE TITLE
BWAPI 3.7.5 in releases is a debug build

### ISSUE THREAD

**Issue by HarmGriffioen** [bwapi/bwapi#663]
BWAPI 3.7.5 is using Microsoft.VC90.DebugCRT, which is no problem when Visual studio is installed on your system, but when it is not, this results in an error. Building it for release should solve the problem I think.

**Comment by heinermann** [comment]
BWAPI is built for both release and debug targets. The debug target will throw an error, but you can still use the release target.

In addition, BWAPI 3.7.x is deprecated.
