### ISSUE TITLE
Total damage dealt by unit

### ISSUE THREAD

**Issue by pmichel31415** [bwapi/bwapi#665]
Is there a way to access or compute the total damage dealt by (and/or to) a unit over the game?

**Comment by heinermann** [comment]
Yes.

See [Game::getDamageFrom](https://bwapi.github.io/class_b_w_a_p_i_1_1_game.html#a90d81ed614f211a6974eaca2a7c67a5a) and [Game::getDamageTo](https://bwapi.github.io/class_b_w_a_p_i_1_1_game.html#ae8d78aaa9aaa835658d0964cb4207683).

Does this solve the issue?
