### ISSUE TITLE
Terran Academy costs 200 minerals in SC 1.16.1

### ISSUE THREAD

**Issue by neumond** [bwapi/bwapi#670]
Currently Unittypes show value of 150, but in game it's 200 (without injection also, running purely starcraft.exe). May be it's only my installation of SC..

**Comment by heinermann** [comment]
http://wiki.teamliquid.net/starcraft/Academy

Looks like 150.

**Comment by neumond** [comment]
Narrowed down the problem. Looks like in good old days academy cost 200 minerals http://www.gamefaqs.com/pc/25418-starcraft/faqs/2355?print=1 . Removing patch_rt.mpq increases it from 150 to 200, I thought this file was merely a translation pack. BWAPI can't deal with localized SC, drawTextScreen outputs pixel garbage.
