### ISSUE TITLE
[WINE] PIPE_NOWAIT flag is not implemented, server/client logic unavailable

### ISSUE THREAD

**Issue by heinermann** [bwapi/bwapi#671]
This causes Starcraft/BWAPI to freeze if the workaround flag `shared_memory=OFF` is not set. This disables the BWAPI server/client bridge.

[WineHQ Bug#17195](https://bugs.winehq.org/show_bug.cgi?id=17195) - Currently in STAGING.

Note: This is replacing the messy #375

**Comment by N00byEdge** [comment]
This is supposed to be fixed in WINE 2.5

**Comment by heinermann** [comment]
Awesome, thanks! Note that WINE **stable** is behind, may want to try the **development** version. Can someone verify the fix?

**Comment by heinermann** [comment]
Since this was fixed in WINE-development back in March, I will now close the issue.
