### ISSUE TITLE
Update BWAPI to support Starcraft 1.17.0

### ISSUE THREAD

**Issue by heinermann** [bwapi/bwapi#673]
Starcraft: Broodwar is about to receive a 1.17.x update. BWAPI needs to be capable of updating to a new Starcraft version.

Here is a checklist of things that need to be updated.

Note: New addresses are using a base of 0x00400000.
Note: Items crossed out were removed in an effort to reduce the number of offsets.
- [x] Support actually loading BWAPI (SDrawRealizePalette is no longer exported by Storm.dll)
- [ ] Support for a dynamic base address for offsets.
- [ ] Offsets need to be updated.
  - [ ] Player Information
    - [x] PlayerResources (Old = 0x0057F0F0)
    - [ ] PlayerVictory (Old = 0x00650974)
    - [x] startPositions (Old = 0x0058D720)
    - [x] ForceNames (Old = 0x0058D5BC)
    - [ ] Players (Old = 0x0057EEE0)
    - [ ] PlayerDownloadStatus (Old = 0x0068F4FC)
    - [ ] playerStatusArray (Old = 0x0057F0B8)
  - [ ] Alliance and Vision
    - [x] Alliance (Old = 0x0058D634)
    - [x] PlayerVision (Old = 0x0057F1EC)
    - [ ] ReplayVision (Old = 0x006D0F18)
    - [ ] ReplayRevealAll (Old = 0x006D0F1C)
  - [ ] Code Patches/hacks
    - [ ] ServerMenuIn (Old = 0x004DD5A2)
    - [ ] ServerMenuOut (Old = 0x004DD5C9)
    - [ ] OpponentStartHack (Old = 0x004B995D)
    - [ ] SingleSpeedHack (Old = 0x004D99FB)
  - [ ] Menu speed hacks
    - [ ] commonSwishControllers (Old = 0x005129EC, New = 0x00503D78, but address placement of other common controllers has changed, thus we need a new method for this (probably code patch or direct dialog editing?))
    - [ ] gluCustmSwishController (Old = 0x0051A9F0)
    - [ ] gluCmpgnSwishController (Old = 0x00512B10)
    - [ ] gluScoreSwishController (Old = 0x0051A844)
    - [ ] gluChatSwishController (Old = 0x0051A490)
  - [ ] Command management
    - [ ] sgdwBytesInCmdQueue (Old = 0x00654AA0)
    - [ ] TurnBuffer (Old = 0x00654880)
    - [ ] BWFXN_sendTurn (Old = 0x00485A40)
    - [ ] BWFXN_QueueCommand (Old = 0x00485BD0)
  - [ ] Speed and Latency
    - [ ] GameSpeedModifiers (Old = 0x005124D8)
    - [ ] GameSpeed (Old = 0x006CDFD4)
    - [ ] LatencyFrames (Old = 0x0051CE70)
    - [ ] FrameSkip (Old = 0x005124D4)
    - [ ] Latency (Old = 0x006556e4)
  - [ ] Dialog and Drawing
    - [x] ~~GenericDlgInteractFxns (Old = 0x005014AC)~~
    - [x] ~~GenericDlgUpdateFxns (Old = 0x00501504)~~
    - [ ] DialogList (Old = 0x006D5E34)
    - [ ] FontBase (Old = 0x006CE0F4) (We should get rid of this, it causes problems for non-english versions)
    - [ ] GameScreenBuffer (Old = 0x006CEFF0)
    - [ ] ScreenLayers (Old = 0x006CEF50)
    - [x] PlayerColors (Old = 0x00581DD6)
  - [ ] DirectDraw Hacks
    - [ ] GamePalette (Old = 0x006CE320)
    - [ ] DDInterface (Old = 0x006D5E08)
    - [ ] PrimaryPalette (Old = 0x006D5E0C)
    - [ ] PrimarySurface (Old = 0x006D5E00)
    - [ ] BackSurface (Old = 0x006D5E10)
    - [ ] BWFXN_DDrawDestroy (Old = 0x0041D8B0)
    - [ ] DDrawInitCallPatch (Old = 0x004DB0A2)
  - [ ] Units
    - [ ] UnitNodeList_VisibleUnit_First (Old = 0x00628430)
    - [ ] UnitNodeList_HiddenUnit_First (Old = 0x006283EC)
    - [ ] UnitNodeList_ScannerSweep_First (Old = 0x006283F4)
    - [ ] UnitNodeTable (Old = 0x0059CCA8)
  - [ ] Bullets
    - [ ] BulletNodeTable_FirstElement (Old = 0x0064DEC4)
    - [ ] BulletNodeTable (Old = 0x0064B2E8)
  - [ ] Unit Ordering (We should get rid of these)
    - [ ] UnitOrderingX (Old = 0x0066FF78)
    - [ ] UnitOrderingY (Old = 0x006769B8)
    - [ ] UnitOrderingCount (Old = 0x0066FF74)
  - [ ] Game Mode and State
    - [ ] gameType (Old = 0x00596820)
    - [ ] InReplay (Old = 0x006D0F14)
    - [ ] NetMode (Old = 0x0059688C)
    - [x] CountdownTimer (Old = 0x0058D6F4)
    - [x] ElapsedTime (Old = 0x0058D6F8)
    - [ ] ReplayFrames (Old = 0x006D0F31)
    - [ ] GameState (Old = 0x006D11EC)
    - [ ] gwNextGameMode (Old = 0x0051CE90)
    - [ ] gwGameMode (Old = 0x00596904)
    - [ ] glGluesMode (Old = 0x006D11BC)
    - [ ] g_LocalHumanID (Old = 0x00512688)
  - [ ] Memory Leak
    - [ ] customList_UIDlgData (Old = 0x0051A350)
  - [ ] Unit Selection
    - [ ] ClientSelectionGroup (Old = 0x00597208)
    - [ ] ClientSelectionCount (Old = 0x0059723D)
  - [ ] Inputs
    - [ ] InputProcedures (Old = 0x005968A0)
    - [ ] EventDialogs (Old = 0x006D5E40)
    - [ ] InputFlags (Old = 0x006CDDC0)
  - [ ] Pausing (and frame hook)
    - [ ] isGamePaused (Old = 0x006509C4)
    - [ ] BWFXN_P_IsGamePaused (Old = 0x004D974E)
  - [ ] Strings
    - [x] CurrentMapFileName (Old = 0x0057FD3C)
    - [x] CurrentMapName (Old = 0x0057FE40)
    - [ ] CurrentMapFolder (Old = 0x0059BB70)
    - [ ] SaveGameFile (Old = 0x00685148)
  - [ ] Repair/Refund hooks (can we dump these somehow?)
    - [ ] BWFXN_RefundMinerals (Old = 0x0042ce97)
    - [ ] BWFXN_RefundMineralsReturnAddress (Old = 0x0042ce9e)
    - [ ] BWFXN_RefundGas (Old = 0x0042ceb8)
    - [ ] BWFXN_RefundGasReturnAddress (Old = 0x0042cebe)
    - [ ] BWFXN_RefundMinAndGas2 (Old = 0x0042ced9)
    - [ ] BWFXN_RefundMinAndGas2ReturnAddress (Old = 0x0042cedf)
    - [ ] BWFXN_RefundMinAndGas5 (Old = 0x00453E62)
    - [ ] BWFXN_RefundMinAndGas5ReturnAddress (Old = 0x00453E68)
    - [ ] BWFXN_RefundMin4 (Old = 0x004541C2)
    - [ ] BWFXN_RefundMin4ReturnAddress (Old = 0x004541CD)
    - [ ] BWFXN_RefundGas4 (Old = 0x004541FD)
    - [ ] BWFXN_RefundGas4ReturnAddress (Old = 0x00454204)
    - [ ] BWFXN_RefundMin3 (Old = 0x0045D44D)
    - [ ] BWFXN_RefundMin3ReturnAddress (Old = 0x0045D454)
    - [ ] BWFXN_RefundGas3 (Old = 0x0045D46e)
    - [ ] BWFXN_RefundGas3ReturnAddress (Old = 0x0045D474)
    - [ ] BWFXN_SpendRepair (Old = 0x00467006)
    - [ ] BWFXN_SpendRepairReturnAddress (Old = 0x0046700D)
  - [x] ~~BWFXN_DSoundDestroy (Old = 0x004BC180) (Considering dropping support for this, new = 0x0049EAE0)~~
  - [x] ~~BWFXN_NetSelectReturnMenu (Old = 0x004DC5B0) (Considering dropping support for this, new = 0x00457E50)~~
  - [ ] Player functions
    - [ ] BWFXN_RandomizePlayerRaces (Old = 0x004A9A30)
    - [ ] BWFXN_RandomizeRacePatch (Old = 0x004EF20E)
    - [ ] BWFXN_InitializePlayerConsole (Old = 0x004EE180)
    - [ ] BWFXN_InitPlayerConsolePatch (Old = 0x004EF244)  
  - [ ] Positioning (Map/Mouse) and Sizes
    - [ ] MoveToX (Old = 0x0062848C)
    - [ ] MoveToY (Old = 0x006284A8)
    - [x] MoveToTile (Old = 0x0057F1D0)
    - [ ] Mouse (Old = 0x006CDDC4)
    - [ ] ScreenX (Old = 0x00628448)
    - [ ] ScreenY (Old = 0x00628470)
    - [x] MapSize (Old = 0x0057F1D4)
    - [ ] BWFXN_UpdateScreenPosition (Old = 0x0049BFD0)
  - [ ] Triggers
    - [ ] TriggerVectors (Old = 0x0051A280)
    - [ ] BWFXN_ExecuteGameTriggers (Old = 0x0048A460)
    - [ ] BWFXN_ExecuteGameTrigsCallPatch (Old = 0x004D9798)
  - [x] Supplies/Availability
    - [x] AllScores (Old = 0x00581DE4)
    - [x] UnitAvailability (Old = 0x0057F27C)
  - [x] Upgrade Data
    - [x] UpgradeMaxSC (Old = 0x0058D088)
    - [x] UpgradeLevelSC (Old = 0x0058D2B0)
    - [x] UpgradeMaxBW (Old = 0x0058F278)
    - [x] UpgradeLevelBW (Old = 0x0058F32C)
    - [x] UpgradeProgress (Old = 0x0058F3E0)
  - [x] Tech Data
    - [x] TechAvailableSC (Old = 0x0058CE24)
    - [x] TechResearchSC (Old = 0x0058CF44)
    - [x] TechAvailableBW (Old = 0x0058F050)
    - [x] TechResearchBW (Old = 0x0058F140)
    - [x] ResearchProgress (Old = 0x0058F230)
  - [ ] Map Data
    - [ ] MapTileArray (Old = 0x005993C4)
    - [ ] TileSetMap (Old = 0x006D5EC8)
    - [ ] MiniTileFlags (Old = 0x005993D0)
    - [ ] ActiveTileArray (Old = 0x006D1260)
    - [ ] SAIPathing (Old = 0x006D5BFC)
- [ ] Structure layouts need to be verified.
  - [ ] dialog
  - [ ] CUnit
  - [ ] CBullet
  - [ ] CSprite
  - [ ] CImage
  - [ ] PlayerResources
  - [ ] PlayerInfo
  - [ ] Trigger List
  - [ ] AllScores
  - [ ] SAI_Paths
  - [ ] ContourHub
- [ ] Storm functions are updated
  - [ ] SDrawManualInitialize no longer takes the palette arguments
  - [ ] SDrawCaptureScreen now takes a second argument

**Comment by RElesgoe** [comment]
Hook into BW to disable digital signature verification for your DirectIP SNP module.

**Comment by heinermann** [comment]
DirectIP SNP module appears to be working fine, so signature stuff doesn't need to change.

We need to use some alternative way to refer to offsets with a dynamic base address. Are you aware of any libraries that can do the hooking/detour stuff for us? Given my current position (full time SDE) I don't have the time to maintain old code if there are external libraries that do the same thing.

There are no Storm.dll offsets in BWAPI so Storm detours should work as they have been.

**Comment by RElesgoe** [comment]
What's wrong with the current hooking code? I've used [MinHook](https://github.com/TsudaKageyu/minhook) for hooking WinAPI before, it's pretty simple.
https://gist.github.com/RElesgoe/80fdcb420f915179892cc82ac70cdfa8

Why not just have a global variable that contains BW's base address and change your code to add offsets?

**Comment by heinermann** [comment]
Well right now I need to create some class to handle the offsets with base
address. Previously they were memory addresses casted to references so they
could be used as if they were part of BWAPI(no dereferencing is actually
great).

**Comment by heinermann** [comment]
After pushing 8cb7dda68c and 0103c0b90cf9, BWAPI successfully injects into Starcraft 1.17.0 in its reduced functionality state (yes BWAPI will try to not explode if the version is incorrect).

I've verified that multi-instance works.

**Comment by RElesgoe** [comment]
Under ````Speed and Latency````, what does the ````Latency```` offset refer to? I documented 2 offsets related to latency here: https://www.reddit.com/r/broodwar/wiki/1_17_0_offsets

The ````PlayerDownloadStatus```` array starts at ````0x2689F4````.

**Comment by neivv** [comment]
The 1.16.1 address range from `0x0057F0F0` to `0x005967F0` is a single large structure containing most of the game state. (Saving code just writes/reads those variables in one 0x17700-byte chunk) If the structure layout hasn't changed, several of BWAPI's offsets could be derived from the struct beginning, which is the players' minerals array.

**Comment by RElesgoe** [comment]
I've documented that ````0x1263D4```` is the current player's minerals, however, I haven't checked if it's a single variable or an actual array. Will do some more testing later.

**Comment by neivv** [comment]
It seems that in the unreleased 1.17.0 game struct's address has changed to `0x005263D0` and the size has been kept 0x17700 bytes.

(That would mean that the address you call current player's minerals is actually player 1's minerals, but otherwise it matches really well :p)

**Comment by RElesgoe** [comment]
Just confirmed that ````0x1263D4```` is the start of an 11 element array for player's minerals.

**Comment by heinermann** [comment]
Do you have the structure itself? This would eliminate many offsets.

`Latency` might be the settings option, in which case it would now be incorrect in BWAPI's calculations that use it. I would need to verify.

**Comment by neivv** [comment]
I have text notes which document some of the fields, but not anything that's ready to be throwed in a C header and used:
https://gist.github.com/neivv/b8dada45bcef7a72b7bfcaa55548814c

**Comment by RElesgoe** [comment]
````
0xc4c   char map_path[0x104] (0057FD3C)
0xd50   char map_title[0x20] (0057FE40)
````
New offsets are ````StarCraft.exe + 	0x12701C```` and ````StarCraft.exe + 0x127120````.

**Comment by RElesgoe** [comment]
Found 2 offsets for game speed: ````0x2673A8``` and ````0x2D3130````

**Comment by heinermann** [comment]
Thanks guys, this is great. I think the biggest issues are going to be the
windowed mode, the changes to the Storm function signatures, and dealing
with the stupid refund hooks(which might be easier now given the cleaner
binary).

On Jul 29, 2016 09:38, "RElesgoe" <notifications@github.com> wrote:

Found 2 offsets for game speed: 0x2673A8``` and0x2D3130````

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub
<https://github.com/bwapi/bwapi/issues/673#issuecomment-236229878>, or mute
the thread

**Comment by heinermann** [comment]
@neivv I'm in the process of creating a consumable struct with a combination of our knowledge, I should have it pushed in a couple of days. This should eliminate a significant number(20+?) of individual offsets so that updating them will require much less work.

**Comment by heinermann** [comment]
76034977678 removes 23 offsets after mapping out the super-structure.

**Comment by s7jones** [comment]
What now that Starcraft is getting v1.18?

**Comment by heinermann** [comment]
At the time of writing, there are currently no plans to support 1.18 or future versions.

**Comment by heinermann** [comment]
We will not be supporting anything above 1.16.1 for now. More information will come after the Remaster is released.
