### ISSUE TITLE
Failed to load AI Module

### ISSUE THREAD

**Issue by daviddevore11** [bwapi/bwapi#681]
I have been having trouble with trying to load in a .dll file for a bot I want to try.  No matter what I have tried whenever the match starts I always get, "ERROR: Failed to load AI Module" .  I have both ChaosLauncher and StarCraft to run as administrator to try and avoid any privileges issues.  I have also double and tripled check to make sure that the path name in the file does match exactly what is in the config file path name.  I am at a loss as to why this is not working.  Any suggestions?

**Comment by heinermann** [comment]
What was the issue?
