### ISSUE TITLE
getUnitsInRectangle returns units from the previous game

### ISSUE THREAD

**Issue by ufsqufbqifbqibfuiq** [bwapi/bwapi#682]
Sometimes, when a new game starts, it seems I have getUnitsInRectangle returning some units from the previous game, at their previous position.

It happens a lot with multi-instances games using two dlls.

My call looks like this:
`Position size = Position(TilePosition(Broodwar->mapWidth(), Broodwar->mapHeight()));`
`for (auto&& enemy : Broodwar->getUnitsInRectangle(0, 0, size.x, size.y, IsEnemy)) ...`

It could be an issue with the initialization of `data->unitSearchSize` or `BW::BWDATA::UnitOrderingCount`.

Restarting Starcraft solves the problem, but I must do this for every game. 
I don't have this issue when starting my bot as a BWAPIClient.

**Comment by heinermann** [comment]
Which version of BWAPI?

**Comment by ufsqufbqifbqibfuiq** [comment]
4.1.2

**Comment by heinermann** [comment]
I am unable to reproduce the error. Can you provide an AI module source which reproduces the error?

**Comment by ufsqufbqifbqibfuiq** [comment]
Well I just recompiled the last BWAPI source with VS2015, and this seems fixed. I think I had a mess of an old version of BWAPI.lib with a newer version of  BWAPI.dll... Sorry :(

**Comment by heinermann** [comment]
OK thanks. Reopen this issue if it happens again.
