### ISSUE TITLE
BWAPIClient significantly slower than AIModule

### ISSUE THREAD

**Issue by edran** [bwapi/bwapi#686]
@heinermann I can confirm indeed that BWAPIClient bots seem to be indeed slower than AIModule ones. I currently have a bot that does pretty much the same thing in both modes, and I get 20-30% reduction in average FPSs.

Where should we start investigating possible ways to reach speed parity?

**Comment by bftjoe** [comment]
How would copying data into a named pipe be just as fast as reading shared memory? I don't think this is possible.

**Comment by N00byEdge** [comment]
This is why we still have the module interface.
