### ISSUE TITLE
Failed to find the gameInit and newAIModule function in bwapi-data BWAPI.dll

### ISSUE THREAD

**Issue by Feartheway** [bwapi/bwapi#690]
Ok,  

I have installed sc bw,  
i have got chaoslauncher to launch with 4.1.2 injector and w-mode 1.02
sc comes up in a nice window
i go to multiplayer, brood war, my pc,
i made a profile called robot 1
i start a game with robot 1 and an in game computer ai

then i get this error message
Failed to find the gameInit and newAIModule function in bwapi-data BWAPI.dll

any ideas what i am doing wrong?

![image](https://cloud.githubusercontent.com/assets/23487739/20327148/cd739f12-ab83-11e6-853d-f0128d500d8c.png)

**Comment by spencerduncan** [comment]
Did you just load the API without loading an AI?

**Comment by Feartheway** [comment]
I have moved one step forward ,  i had referenced BWAPI.dll instead of LetaBot.dll
but i am still getting an error

error failed to find gameinit function

I seemed to have to copy the following into windows ... it kept saying they were missing
gmp-vc90-mt-gd.dll	
gmp-vc90-mt.dll	
mpfr-vc90-mt-gd.dll	
mpfr-vc90-mt.dll	


![image](https://cloud.githubusercontent.com/assets/23487739/20328781/7e483e1c-ab8c-11e6-8b14-b7161d2a12da.png)

**Comment by Feartheway** [comment]
i tried with AIUR.dll and got the same error...

error failed to find the gameInit function

**Comment by spencerduncan** [comment]
But you got LetaBot to work?

**Comment by heinermann** [comment]
Were those bots compiled against BWAPI 4.1.2?

**Comment by Feartheway** [comment]
I have no idea, probably not, they were off this website
http://sscaitournament.com/index.php?action=scores      how do i check?

**Comment by Feartheway** [comment]
they come bit a bot.dll and bwapi.dll they both go in the 
C:\Program Files (x86)\Starcraft\bwapi-data\bots\iron  folder right?
i have been just putting both into C:\Program Files (x86)\Starcraft\bwapi-data\
but thats getting really messy.

**Comment by Feartheway** [comment]
Do i have to put the BWAPI.dll somewhere else? specific to that bot?  i have a feeling it should be in the chaos launcher plugins folder?

**Comment by Feartheway** [comment]
Ok, I have put the iron bot bwapi.dll in the top directory of 
C:\Program Files (x86)\Starcraft\bwapi-data\
I have put iron bot in
C:\Program Files (x86)\Starcraft\bwapi-data\bots\iron

it is now working but playing really fast,   any way to slow down the bot?
is there a tutorial on using 2 bots 1vs1?

**Comment by Feartheway** [comment]
ok thx for all the help i seem to have got it all up and running,
for two different bots its just a  first bot path, second bot path,

**Comment by edran** [comment]
@Feartheway FYI, there's an helpful Facebook group if you have any questions about BWAPI or you need help with setting things up: https://www.facebook.com/groups/bwapi/

Otherwise try asking in the IRC channel ( #bwapi @ freenode).
