### ISSUE TITLE
UnitType upgrades() method returns wrong upgrades for hydralisk

### ISSUE THREAD

**Issue by gurkenlabs** [bwapi/bwapi#692]
The following issue was detected in BWAPI 4.1.2:
As I implemented an upgrade mechanism for a zerg bot, I was wondering why it was always returning Zerg_Melee_Attacks for an hydra upgrad insted of Zerg_Missile_Attacks.
I looked into the implementation and found that it was just implemented that way in the UnitType.cpp.

I think this is just a bug, please correct me if there is any reason why it should return Melee for hydra.

**Comment by heinermann** [comment]
Fixed.
