### ISSUE TITLE
buffer read overflow in StrCopy from bwapi/BWAPIClient/Source/Convenience.h

### ISSUE THREAD

**Issue by ufsqufbqifbqibfuiq** [bwapi/bwapi#693]
I got some random crashes with the Game::sendText method (I'm using the "develop" branch).

I think I found a bug:

in `GameImpl::vSendTextEx:`
https://github.com/bwapi/bwapi/blob/38343b0263e7de72f4a7ab66d897a879b4a97802/bwapi/BWAPIClient/Source/GameImpl.cpp#L633
```
char buffer[256];
VSNPrintf(buffer, format, arg);
addCommand(BWAPIC::Command(BWAPIC::CommandType::SendText, addString(buffer), toAllies ? 1 : 0));
                                                                       ^
                                                                    256 bytes

```
in `addString`:
https://github.com/bwapi/bwapi/blob/38343b0263e7de72f4a7ab66d897a879b4a97802/bwapi/BWAPIClient/Source/GameImpl.cpp#L45
```
StrCopy(data->strings[data->stringCount], text);
                     ^                      ^
                 1024 bytes              256 bytes
```

1024 bytes because:
https://github.com/bwapi/bwapi/blob/38343b0263e7de72f4a7ab66d897a879b4a97802/bwapi/include/BWAPI/Client/GameData.h#L147
`char strings[MAX_STRINGS][1024];`

`in StrCopy:`
https://github.com/bwapi/bwapi/blob/38343b0263e7de72f4a7ab66d897a879b4a97802/bwapi/BWAPIClient/Source/Convenience.h#L21
```
strncpy(dst,     src,         N-1);
         ^        ^            ^
   1024 bytes   256 bytes     1023 

```

I think it doesn't crash because strncpy stop reading src after the null terminator.

But in the develop branch, strncpy has been replaced with std::copy
https://github.com/bwapi/bwapi/blob/develop/bwapi/BWAPIClient/Source/Convenience.h#L22
```
std::copy(src,    src     +    N,       dst);
           ^      ^            ^         ^
   256 bytes   256 bytes     1024     1024 bytes
   
```
And then it occasionally crashes.

The fix is probably to change
    ` char strings[MAX_STRINGS][1024]; `
to 
     `char strings[MAX_STRINGS][256]; `
     
or make sure no buffer passed to `addString` is less than 1024 bytes.

Same problem with` GameImpl::vPrintf`
`GameImpl::vDrawText` is okay with a 2048 bytes buffer

I didn't look in other files.

**Comment by qtoncoding** [comment]
The usage currently is using the size of dest as the number of bytes to copy. With strncpy(src, dest, num), if num is larger than src's length, it will pad dest with 0s until num is reached (this can still trample over memories), std::copy will just do copy until first == last, so it will happily copy garbage over. Honestly, the best way to go about this is to just use std::string instead of char*, then this whole thing won't be a problem. Otherwise, the alternative is to modify StrCopy to copy src's length to dest, then if the behavior of strncpy is actually intended, then we can zero out there too.

**Comment by qtoncoding** [comment]
#695 Fix in this PR

**Comment by heinermann** [comment]
You're right. std::copy is incorrect. std::strncpy is the appropriate function.

**Comment by qtoncoding** [comment]
then in this case just reverting that change in develop should be good
