### ISSUE TITLE
isBuildable yields True even in some unbuildable tiles with doodads

### ISSUE THREAD

**Issue by neumond** [bwapi/bwapi#696]
![isbuildable](https://cloud.githubusercontent.com/assets/3260024/21515143/7a350f32-cce6-11e6-9143-4885a7576e48.png)
I've prepared picture explaining the bug. Grey scheme is made by simple calling isWalkable/isBuildable for every possible point in map. You can see some tiles are still isBuildable while they're actually not. Affected version of bwapi is 4.1.2.

**Comment by neumond** [comment]
![isbuildable2](https://cloud.githubusercontent.com/assets/3260024/21515280/b2bc9a9a-cce7-11e6-9a1e-6b44d09ec1dd.png)
Zoomed in

**Comment by heinermann** [comment]
*flips table*

**Comment by neumond** [comment]
Lol, irritating bug with long history? How can I help?

**Comment by neumond** [comment]
ok, i'll make multiple tests (probably some automatized) on my side.

**Comment by heinermann** [comment]
There's an automated map test that you can add to (TestAIModule). You can simply add some doodads and check their buildability. I will do this myself at some point anyway.

**Comment by neumond** [comment]
Multiple maps affected https://gist.github.com/neumond/79dbd52abcf80db4afabf309c32c8f17
Have to check them manually though, that's just isBuilable=true tiles having isWalkable=false.

**Comment by Cmccrave** [comment]
This is still a relevant issue @heinermann, as I mentioned on discord yesterday.
https://liquipedia.net/starcraft/Roadkill
![image](https://user-images.githubusercontent.com/25108498/53776395-ee5b0c80-3ec3-11e9-98d4-c9df0c68ae8d.png)

**Comment by heinermann** [comment]
Are you using the client or module?

**Comment by Cmccrave** [comment]
Module, version 4.2 release

**Comment by N00byEdge** [comment]
Possibly related OpenBW logic for this, I will also take a look at it after work: https://github.com/OpenBW/openbw/blob/master/bwgame.h#L19312-L19318

**Comment by N00byEdge** [comment]
Fixed in https://github.com/bwapi/bwapi/commit/76399251ae556f123e12d185006be82503b3dabb

**Comment by N00byEdge** [comment]
Fixed in https://github.com/bwapi/bwapi/commit/76399251ae556f123e12d185006be82503b3dabb
