### ISSUE TITLE
OSX: Unhandled exception: unimplemented function . called in 32-bit code

### ISSUE THREAD

**Issue by muandrew** [bwapi/bwapi#699]
BWAPI 4.1.2, wineskin 2.6.2, wine engine ws9Wine 1.9.24, osx 10.11.6
I'm not sure where to start debugging this.
I can launch windowed mode BW with ChaosLauncher.
The crash below occurs when I try to inject BWAPI.
```
Unhandled exception: unimplemented function . called in 32-bit code (0x7b42dd12).
Register dump:
 CS:001b SS:0023 DS:0023 ES:0023 FS:101f GS:000f
 EIP:7b42dd12 ESP:02caf564 EBP:02caf5d8 EFLAGS:00000246(   - --  I  Z- -P- )
 EAX:7b418959 EBX:7b42dc9e ECX:00000000 EDX:00000000
 ESI:00000002 EDI:15034a20
Stack dump:
0x02caf564: *** Invalid address 0x02caf564 ***

0203: sel=101f base=7ff90000 limit=00000fff 32-bit rw-
Backtrace:
=>0 0x7b42dd12 (0x02caf5d8)
0x7b42dd12: -- no code accessible --
Modules:
Module	Address			Debug info	Name (0 modules)
Threads:
process  tid      prio (all id:s are in hex)
00000008 Chaoslauncher.exe
	00000029   -1
	00000009    0
0000000e services.exe
	00000020    0
	0000001f    0
	00000014    0
	00000010    0
	0000000f    0
00000012 winedevice.exe
	0000001e    0
	00000019    0
	00000018    0
	00000013    0
0000001c plugplay.exe
	00000022    0
	00000021    0
	0000001d    0
00000023 explorer.exe
	00000028    0
	00000027    0
	00000026    0
	00000025    0
	00000024    0
0000002a (D) (null)
	0000002e    0 <==
	0000002d    1
	0000002b    0
System information:
    Wine build: wine-1.9.24
    Platform: i386
    Version: Windows XP
    Host system: Darwin
    Host version: 15.6.0
```

**Comment by heinermann** [comment]
Have you filed an issue with WINE?

**Comment by muandrew** [comment]
Not yet, I'll try updating to WINE 2.1 and find out.

**Comment by muandrew** [comment]
After switching to wine 2.1 and using winedbg I found the following error.
```
Call from 0x7b42746f to unimplemented function msvcr120.dll.?_Id@_CurrentScheduler@details@Concurrency@@SAIXZ, aborting
Unhandled exception: unimplemented function . called in 32-bit code (0x7b42746f).
```
It seems to be tracked by https://bugs.winehq.org/show_bug.cgi?id=40219

However I recently found out that I was supposed to be using WINEARCH=win32  when creating a wine-prefix and now I am encountering an issue described by https://github.com/bwapi/bwapi/issues/375 and am currently asking for help in the facebook group at https://www.facebook.com/groups/bwapi/permalink/10158289547170261/

**Comment by heinermann** [comment]
Yep this happens when BWAPI is injected when the process is just started (Chaoslauncher, etc). But if you use something that injects it while the process is running it should be fine. I've added a workaround for 4.2.0 already but the underlying issue is with WINE, linked from #375. It's a very rare occurrence that happens to be unique with StarCraft Broodwar so I don't expect anyone to take on that issue any time soon. But if you +1 it or whatever the equivalent is in their system it should raise awareness.

**Comment by heinermann** [comment]
See #672.

**Comment by muandrew** [comment]
So I have tried using both Winject.exe (v1.7a& v1.7b)
winject-1.7b /dllname:"c:\BWAPI.dll" /exename:starcraft.exe /extended
"Can't open process (###)"

The directory structure is along the lines of
```
c/
--BWAPI.dll
--winject
--Program Files/
----BWAPI/
----StarCraft/
------StarCraft.exe
------bwapi-data/
```
my setup is the following
```
osx: 10.11.6
wine: 2.1
WINEARCH=win32
winetricks -q vcrun2013
StarCraft anthology: 1.15.2
BW-1161.exe (patch)
BWAPI_412_Setup.exe
```

Are you developing in a *nix environment or do you just use Windows? And if you develop with *nix would you mind sharing your os and the version of wine you are using?

Thanks >.>

**Comment by heinermann** [comment]
I actually don't develop in WINE, but I was trying to figure out all these issues back when I had a Linux machine.

**Comment by heinermann** [comment]
I'm assuming this is the same issue that was referenced earlier, so I'll close as duplicate. Let me know if there are issues with using BWAPI 4.4.

**Comment by muandrew** [comment]
Not sure, but thanks for coming back to this issue anyway. Cheers!
