### ISSUE TITLE
Reading hotkeys?

### ISSUE THREAD

**Issue by alexpineda** [bwapi/bwapi#703]
Is there a way to read assigned and pressed hotkeys in a replay with BWAPI?

**Comment by heinermann** [comment]
Nope. Sounds like a feature request.

**Comment by alexpineda** [comment]
Is this issue enough to act as a feature request or are there further actions I need to take? Is there a priority feature list somewhere I can estimate when/if this will be implemented? Thank you!

**Comment by heinermann** [comment]
Yep this is enough. Thanks. It might sit here for a while though.

**Comment by heinermann** [comment]
Looking back I'm not sure what the ask is exactly. Do you mean reading saved selection groups?

**Comment by alexpineda** [comment]
I believe the intent was to be able to display fpv a bit better although if it's of no interest to you please close as I no longer require this.
