### ISSUE TITLE
develop branch performance issues?

### ISSUE THREAD

**Issue by squeek502** [bwapi/bwapi#706]
From IRC:

```
<squeek502> for some reason i got really bad performance issues when i tried the develop branch
<squeek502> anyone else experience that? over time my fps would just constantly drop lower and lower
<squeek502> even without a bot loaded
<ratiotile> lol I thought it was just my bot
<Adakite> are you both using clients or modules
<squeek502> module
<ratiotile> client
```

Just want to confirm/deny whether or not this is something known, or if it's unique to me.

**Comment by heinermann** [comment]
I'm not experiencing this. Is there a specific map this occurs on?
Note you can use the `/fps` command to see fps.

If you mean frame drop based on number of units on the map then this is unfortunately a known issue.

**Comment by squeek502** [comment]
Will give it another shot and report back with more info.

**Comment by squeek502** [comment]
Was unable to reproduce this on my end as well. Not sure what happened. To give a little more information, the issue was that my FPS would drop to like 10 over the first 2 minutes or so of a game. But, yeah, looks like this might have just been an issue on my end, and I can no longer reproduce it. My bad.
