### ISSUE TITLE
getUnitsInR*, getClosestUnit* can be either optimized or documented as slow

### ISSUE THREAD

**Issue by kvakvs** [bwapi/bwapi#709]
The mentioned group of functions works by iterating over all units and calling a slow distance function on each. This can be improved by introducing a rough grid, where each unit registers itself as it moves (as its coords change). Then iterating over closest units will be much faster.

A point to mention is that adding this feature will immensely help C++ bots but not help Java and other language bots at all, because for them calling into C++ is expensive. So this could become a C++ library instead and the functions could be documented as slow and inefficient.

I might be able to offer a PR with C++ implementation once I have created it for my bot.

**Comment by heinermann** [comment]
> The mentioned group of functions works by iterating over all units and calling a slow distance function on each. This can be improved by introducing a rough grid, where each unit registers itself as it moves (as its coords change). Then iterating over closest units will be much faster.
This is what it does. The "slow distance" (actually the fast distance) function is for checking if it's within a certain radius, within the rectangle you specified.

**Comment by heinermann** [comment]
Otherwise on average, if your rectangle is small, it's closer to logarithmic in complexity.
