### ISSUE TITLE
Idea for a plugin

### ISSUE THREAD

**Issue by stereokai** [bwapi/bwapi#713]
@heinermann

I had an idea for a plugin to help practice the keyboard shortcuts in Starcraft. The plugin is very simple in purpose: every time you click on an order button in the unit control panel (the pabel on the bottom-right), a small box (around 100x100 pixels) with the letter of the corresponding hotkey would blink for a fraction of a second in the middle of the screen.

Is it possible to do that with BWAPI? Thanks you :)

**Comment by heinermann** [comment]
It isn't with the current interface, sorry. This is out of scope for BWAPI.

You could theoretically make a hack to be able to do this though, but I don't have the time to investigate the details on how it would be done.

**Comment by stereokai** [comment]
Thanks

**Comment by heinermann** [comment]
If you were determined enough you could figure out the clicking part, and I can provide the drawing code.

**Comment by stereokai** [comment]
Unfortunately I don't have the time and determination to invest in diving into this for the technicalities and overcoming the learning curve. If it were a straightforward task, I would be more motivated to go the length. Thanks for chiming in anyway :)
