### ISSUE TITLE
The game loaded by Chaoslauncher crash

### ISSUE THREAD

**Issue by yangwenhaosms** [bwapi/bwapi#714]
I want to do some research with StarCraft and install the packages by following the instructions at https://github.com/alibaba/gym-starcraft
When I open the Chaoslauncher and start the BWAPI 4.2.0 Injector [release],the game is loaded in a window. But if I load a map, it would stuck and no more reflection.
If I open the StarCraft directly, the loading would be fine and no stuck.

**Comment by Elias1226** [comment]
My computer is windows10

**Comment by Elias1226** [comment]
![image](https://cloud.githubusercontent.com/assets/23031850/26031424/53b8eb96-38a5-11e7-8b89-12cd08e8e22a.png)
This is the screenshot, the game has no reflection

**Comment by Elias1226** [comment]
[bwapi.txt](https://github.com/bwapi/bwapi/files/999109/bwapi.txt)
This is the bwapi setting content

**Comment by f0ghua** [comment]
I meet the same issue, any solution?

**Comment by heinermann** [comment]
What is the message at the beginning of the game?

**Comment by heinermann** [comment]
Closing as there is not enough information and the issue has not been updated with any more information. If you still have issues please create a new issue.
