### ISSUE TITLE
Using BWAPI AIs in the Singleplayer Campaign

### ISSUE THREAD

**Issue by honzi** [bwapi/bwapi#717]
Since the full StarCraft game is now available to everyone, I think a GitHub issue for the campaign should exist.

Based on my current knowledge: ChaosLauncher restricts access to the campaign for legal reasons, which results in BWAPI AIs not being able to attempt campaign missions. I do not believe that this restriction should still exist, but I also have no knowledge of updating the ChaosLauncher or knowledge of if BWAPI would still properly function when these missions are started, so this is more of a placeholder issue to facilitate discussion and ensure this would be possible when such restrictions are removed.

**Comment by heinermann** [comment]
Chaoslauncher and BWAPI both have always worked for the campaign. There was never any restriction. I'm confused what the issue is?

**Comment by honzi** [comment]
Oh? The ChaosLauncher version 0.5.4.4 I downloaded from https://github.com/downloads/MasterOfChaos/Chaoslauncher/Chaoslauncher.zip seems to be multiplayer-only and the campaign is unable to be loaded. It makes the clicking beep sound when you click on any of the three races but doesn't load anything. I have Windows 10 and I tried running it as admin, not as admin, and even without any plugins checked.

Everything I was able to find via searching online mentioned that often these non-Blizzard downloads removed singleplayer to save space and/or avoid legal trouble, and I was unable to find any ChaosLauncher documentation that described this issue in any fashion.

I made sure it was running 1.16.1 and my custom AI works without issues when doing 1v1s.

**Comment by ratiotile** [comment]
It is known that BWAPI doesn't work with the **original** Starcraft campaign, but it should work with the **expansion** Broodwar campaign.

**Comment by honzi** [comment]
I tried all original and expansion campaigns, but all have the same issue: just the click beep sound and then nothing happens.

**Comment by heinermann** [comment]
@honzi Are you sure you don't have multiple installations? If you click on a campaign and it just beeps and does nothing, that means your Starcraft installation itself does not have the campaign. (So non-BWAPI)

@ratiotile why doesn't it work with the original campaign?

**Comment by N00byEdge** [comment]
I have an original install from the CD, with BWAPI on top of it, I've never gotten the SP campaign to load on it. Expansion has always worked fine for me though. Can we provide you with any hashes of any files to make sure everything is as it should be?

**Comment by ZerGreenOne** [comment]
I assume that you can load the campaign when Chaoslauncher isn't being run?

**Comment by heinermann** [comment]
Does it work if you still run Chaoslauncher but not BWAPI?

**Comment by neoedmund** [comment]
I'm just passing by. I think BWAPI should have no issue with campaigns. About 8 years ago, I wrote AI for completing some of the missions. https://github.com/neoedmund/neoe-bw-ai-missions  , just as reference.

**Comment by honzi** [comment]
Seems this was just an issue of missing campaign files. ¯\\\_(ツ)\_/¯
I blame this issue on all the drama caused by requiring 1.16.1 instead of Blizzard's updated version.

**Comment by heinermann** [comment]
Thanks for the update.
