### ISSUE TITLE
Faking SC installation for build process

### ISSUE THREAD

**Issue by Kruecke** [bwapi/bwapi#722]
Hey guys,

I have a build server where I build BWAPI 4.2 as an dependency for my bot. This works just fine as long as I just pass `/target:BWAPILIB` to `msbuild`. Now for deployment I would like to build a copy of `BWAPI.dll` as well but there is a problem with the `BWAPI` project. There is a post-build event that runs `copyToTarget.vbs` to install `BWAPI.dll` to the Starcraft installation location. Well, on my build server there is no installation of Starcraft. So the build fails at the very last step where it tries to run that script which returns code 3:

> 2017-06-14T13:40:48.9415374Z   Failed to find Starcraft directory.

I mean there's really no reason to have a Starcraft installation on the build server so the first question would be **How do I make the script believe that there is a Starcraft installation somewhere?** I mean I want that copy of `BWAPI.dll` anyways so maybe I can even (mis-)use this script for my purposes here.

Of course I tried to fix this issue on my own but there is a strange behavior I just don't understand. If I look at the script there are the following lines.

```
targetPath = objShell.RegRead("HKCU\SOFTWARE\Blizzard Entertainment\Starcraft\InstallPath")
if not objFS.FolderExists(targetPath) then
  targetPath = objShell.RegRead("HKLM\SOFTWARE\Blizzard Entertainment\Starcraft\InstallPath")
  if not objFS.FolderExists(targetPath) then
    WScript.Echo("Failed to find Starcraft directory.")
    WScript.Quit(3)
  end if
end if
```

I expected there to be a registry key on my local computer (where I can build everything without any problem) but this `InstallPath` just doesn't exist. Also if I run the script from the (VS) command line I get the error: "Failed to find Starcraft directory." But if build everything either from within Visual Studio or with `msbuild` the script works just fine. **Can someone explain me how this can be the case?** Is the entry created at some point in the build process!? Or how is the script able to figure out my (correct) installation location.

It is a little bit irritating that the build fails at that point in time. Maybe the build process can be improved here? Everything else works just perfectly.

Thanks for your help,
Florian

**Comment by jaj22** [comment]
If you check regedit on your local computer, you should find the key in `HKLM\Software\Wow6432Node\Blizzard Entertainment\Starcraft\InstallPath`

I think the way this works is that for 32-bit programs, Windows maps Software to Software\Wow6432Node, while for 64-bit programs, it doesn't. Hence 64-bit programs (or scripts executed by 64-bit programs) need to add the Wow6432Node part explicitly.

The behaviour you're seeing suggests that VS uses the 32-bit version of VBScript (which makes sense given that VS is 32-bit), while the command prompt uses the 64-bit version of VBScript.

**Comment by Kruecke** [comment]
Thanks for your help. I see how it works now.

Since I'm not allowed to edit the registry on my build server, I worked around the script by replacing it with an empty one, just before the build. It's not a nice solution but it meets my demands so far.
