### ISSUE TITLE
Color Global Variable always initialized to Black when building in Debug

### ISSUE THREAD

**Issue by ZerGreenOne** [bwapi/bwapi#730]
BUILDING IN DEBUG, if I write
`BWAPI::Color testColor = Colors::Blue;`
as a global variable, and
`Broodwar->drawCircle(CoordinateType::Mouse,0, 0, 2, testColor);`
in onFrame, then the circle around the mouse will be in Colors::Black rather than Colors::Blue.

I like debugging my projects in "Debug", because when debugging it never skips over any breakpoints due to optimization, and it gives me nicer error messages when Broodwar crashes.

When I compile the project in "Release", it works fine.

While we are waiting for this to be fixed, a alternate solution is to instead use
`BWAPI::Color testColor = Color(0,0,255);`
or in general
`BWAPI::Color testColor = Color(r,g,b);`
which works even in "Debug"

**Comment by jaj22** [comment]
Is that in 4.2.0 or 4.1.2? The constructor for Color was made constexpr in 4.2.0, which should in theory fix this.

**Comment by ZerGreenOne** [comment]
Version 4.1.2.4708 DEBUG according to the message that pops up when I start an AI.

**Comment by ZerGreenOne** [comment]
Version 4.1.2.4708 DEBUG according to the message that pops up when I start
an AI.

**Comment by heinermann** [comment]
Can you test in 4.2.0?

It should be an easy fix.

**Comment by ZerGreenOne** [comment]
Ahh, I'm fairly certain I did test this, I'm fairly certain it was still a problem, I should have updated this comment. Really quite old and cold now. I'll look into it.

**Comment by ZerGreenOne** [comment]
Tested, was fixed.
