### ISSUE TITLE
  ERROR: Failed to load the AI Module 

### ISSUE THREAD

**Issue by topdavidwu** [bwapi/bwapi#732]
The Version of bwapi 4.1.2 can load sucessfully the exampleAIModule.dll ,but it can not load the other AI
 Module , such as "Overkill.dll" , "UAlbertaBot.dll"

1  Loading the ai module, error screenshot:

![default](https://user-images.githubusercontent.com/29670792/28558805-1f58534e-7146-11e7-95b4-40c4d0920444.png)

2 After click the button "Retry", an error occurred:

![1](https://user-images.githubusercontent.com/29670792/28572742-dc28d406-717a-11e7-9246-528660a87cfd.jpg)

ERROR: Failed to load the AI Module  "bwapi-data/AI/Overkill.dll"

What is the reason？How can I solve this problem?

**Comment by N00byEdge** [comment]
Try using the bwapi.dll that comes with the bots, not just your own version. All bots are made for a specific version of BWAPI and may not be compatible with another one.

**Comment by topdavidwu** [comment]
thank you , how to find the version of bwapi and visual studio for the specific bots?

**Comment by heinermann** [comment]
Is this still an issue? It just seems like you're using a compiled UAlbertabot with a different version bwapi.dll?

**Comment by N00byEdge** [comment]
BWAPI was built in debug. Use the matching BWAPI release.
