### ISSUE TITLE
Release mode compiling failed in example

### ISSUE THREAD

**Issue by steveWin32** [bwapi/bwapi#746]
I can't seem to get it to work.
Visual Studio 2017 (v15.3.5)

The object or library file '../lib/BWAPI.lib' was created with an older compiler than other objects; rebuild old objects and libraries	

![xxy](https://user-images.githubusercontent.com/23382734/34395551-ffc0f7e4-eb15-11e7-82cc-9ca00ea50997.PNG)

I tried building BWAPI.lib (Source code) but it doesnt work at all. I get errors such as

Cannot open include file: 'cctype': No such file or directory (compiling source file Enter_Transport.cpp)

![xxx](https://user-images.githubusercontent.com/23382734/34395543-eaaf995a-eb15-11e7-8942-9d3e1079c6b8.PNG)

Debug compile works but debug lib/dll runs slow as i was heard and used Release instead. I don't want to downgrade to Visual Studio 2015. People kept saying it works but it doesn't. Anyone have a workaround for this. 

Tried redownloading the IDE but still didn't work.
Downloaded a fresh copy of bwapi but didn't work.
I also updated the Windows SDK to use the latest version

**Comment by dgant** [comment]
This pops up seemingly every day now. And everyone who tries building 4.2.0 themselves struggles with the absent svnrev.h

It may be worth publishing a 4.2.0 with 2017 libs (4.2.1?).

**Comment by heinermann** [comment]
Are you able to view [the latest build artifacts](https://ci.appveyor.com/project/heinermann/bwapi/build/4.2.0.90/artifacts)? Let me know if that works or not and I can produce a new version.

**Comment by andrewsilva9** [comment]
I am running into the same issue with the latest build linked. Is there a way to workaround the issue with a different example / tutorial?

**Comment by N00byEdge** [comment]
@andrewsilva9 Yeah. Git clone BWAPI and checkout the version you want. Then rebuild BWAPI and then your bot. Works like a charm.

**Comment by andrewsilva9** [comment]
I'll give that a shot. Thanks!

**Comment by heinermann** [comment]
I rebuilt 4.2.0 in AppVeyor here: https://ci.appveyor.com/project/heinermann/bwapi/build/4.2.0.100/artifacts

**Comment by heinermann** [comment]
I included these artifacts in the release: https://github.com/bwapi/bwapi/releases/tag/v4.2.0

**Comment by andrewsilva9** [comment]
The latest build worked, thank you! In the future, should I just follow this guide: https://github.com/bwapi/bwapi/wiki/Compile-BWAPI to build it myself? If this error crops up again that is.

**Comment by heinermann** [comment]
You could, but rebuilding is also as easy as clicking the "rebuild" button in AppVeyor.

**Comment by N00byEdge** [comment]
> You could, but rebuilding is also as easy as clicking the "rebuild" button in AppVeyor.

Pretty sure only you can do that :P

It could work with downloading the repo too if we didn't care about the SVN revs working anymore. Is there any reason to keep them?

**Comment by heinermann** [comment]
It's a way to version. We can use a default if git isn't available. I'm actually hoping to get rid of it at some point.

**Comment by chriscoxe** [comment]
I have solved it without needing to rebuild BWAPI 4.2.0.  Please refer to my comment at https://github.com/bwapi/bwapi/issues/737#issuecomment-402451953.

**Comment by heinermann** [comment]
As of BWAPI 4.4, the BWAPILIB project is included in bot modules. Try that.
