### ISSUE TITLE
std::hash specialization of BWAPI::Point missing

### ISSUE THREAD

**Issue by N00byEdge** [bwapi/bwapi#750]
Specializing `std::hash` for `BWAPI::Point` would allow bot writers to easily create hashsets of their positions. 

This should also be easy, since it's not hard at all to cast 2 32 bit number to a 64 bit one and then use the built-in 64 bit hash in the library that the bot author uses.

I therefore propose the hash returning something in the way of
`std::hash<long long>{}((((long long)p.x) << 32) | ((long long)p.y))`

**Comment by N00byEdge** [comment]
As @heinermann pointed out, point coords fit in 16 bits, and we can therefore avoid working with 64 bit ints on 32 bit platforms:

`std::hash<int>{}((((long long)p.x) << 16) | ((long long)p.y))`

**Comment by heinermann** [comment]
Added.
