### ISSUE TITLE
On my machine Starcraft.exe takes up 25% CPU (one full core) when just waiting on the multiplayer menu.

### ISSUE THREAD

**Issue by s7jones** [bwapi/bwapi#752]
As explained in the title, Starcraft is taking up 25% CPU on a 4 core machine whilst waiting in the multiplayer menu.

Presumably the auto GUI methods are just spamming constantly such that there's no break.

**Comment by heinermann** [comment]
Is the CPU throttling option in StarCraft enabled? Do you get the same behaviour without BWAPI?

**Comment by s7jones** [comment]
That fixed it thanks. The CPU is now only about 7%.
