### ISSUE TITLE
getBuildUnit inconsistency

### ISSUE THREAD

**Issue by Venorcis** [bwapi/bwapi#780]
This function is a bit confusing. It has symmetry for SCVs (it returns the building under construction for the SCV or the SCV for the building under construction), but not for other units (it does return the zealot being trained for the gate but it does not return the gate for the zealot being trained). This last case (return the gate that is training the zealot) would be expected to work considering how it works for SCVs, but it does not.

**Comment by dgant** [comment]
"Figure out which building is making which unit by looking for (unit of builder type) with the same position" is done pretty commonly. This would make a nice addition.
