### ISSUE TITLE
replay is twisted

### ISSUE THREAD

**Issue by sijiaxu** [bwapi/bwapi#785]
I has puted a issue at https://github.com/davechurchill/StarcraftAITournamentManager/issues/29 
but I think it maybe more related to bwapi.

the only difference between the usage in Tournament Manager and bwapi's chaos Launch is that TM using injectory tool to inject dll:
injectory.x86.exe --launch StarCraft.exe --inject bwapi-data\BWAPI.dll 
and it seems work fine at TM.

it's really an annoying problems, if the replay can not guaranteed to be correct, locating some bugs will be much harder.

**Comment by sijiaxu** [comment]
I quote the detail issue:

very strange issue.

I use TM to play games. I firstly notice that some replay is strange, seems like bugs in my bot.
so I create a one-one match on two VM, using the same injectory.x86.exe command to start both bots, I watch my bots playing through the game until the end. but when I load the replay to see some detail info,
I found that after about 20 minutes playing, my bot's behavior is totally different from what I saw before, it seems like another bot take over this.
I also log some detail information, like how many unit I own at this time, and it also totally different from what the replay shows. I has tested many time and this situation is continuously happening.

https://github.com/bwapi/bwapi/issues/142
I found the similar issue, Does that mean the replay is not guaranteed to be correct?
it just a BW bugs?

I don't has any clue about why this can happen, has anyone encounter this issue before?
Thanks

**Comment by dgant** [comment]
It's possible for BW to produce corrupt, out-of-sync replays. The usual result is that by the end of the replay the game is in a totally incoherent state and most units aren't moving.

It happens fairly rarely, though. If you've only seen it once or twice I wouldn't worry about it.

**Comment by sijiaxu** [comment]
it seems caused by BWEM's EasyBMP library, although I don't know the detail reason, but when I don't compile with EasyBMP library, everything works fine.
