### ISSUE TITLE
Error when running chaoslauncher.exe

### ISSUE THREAD

**Issue by Marcoux1** [bwapi/bwapi#789]
Hey im new to this scene and I'm getting an error when I click the chaoslauncher.exe 

![image](https://user-images.githubusercontent.com/36140876/39773191-479fdc26-52c5-11e8-96ba-bd69a91c40ea.png)

This is the error im getting, im not sure what it means because the file in question is still at that directory and I can't open it. Can anyone help me out?

**Comment by dgant** [comment]
It looks like you're missing a required Visual C++ distribution. There's a link containing all the distributions you're likely to need at http://www.cs.mun.ca/~dchurchill/starcraftaicomp/all_vcredist_x86.zip

Also, it looks like you're running BWAPI 3.7.5, which is quite old. The most recent version of the API is 4.2.0 and I recommend using it. You may need 3.7.5 to run some older bots, but if you're developing your own 4.2.0 is the way to go.

**Comment by Marcoux1** [comment]
@dgant Thanks for the reply. I am making a bot as a school project and I have been using this tutorial http://www.starcraftai.com/wiki/BWAPI_and_BWMirror_(Java) . I'm sure this tutorial is outdated but another classmate of mine used it too do the same thing and it worked for him so im just doing it with this version, it doesn't have to be very advanced, just has to work. I will update this thread as well if I run into any more errors.

**Comment by Marcoux1** [comment]
@dgant Ok so I ran the .bat in the VC++ file you linked, and it went through and installed everything and i tried to run chaoslauncher and im getting the same error. 

![image](https://user-images.githubusercontent.com/36140876/39814805-c2d9f982-5363-11e8-89b8-a123104c519d.png)

Do I have to restart for those files to finish installing or is there something else going on?

**Comment by Marcoux1** [comment]
When going through the process of opening chaoslauncher and running starcraft with the bwapi plugin, im getting a number of errors. So i figured the best thing for me to do is to post a list of them and maybe we can troubleshoot them individually and some solutions for one thing might fix another problem. 

So when running chaoslauncer.exe i get this:
![image](https://user-images.githubusercontent.com/36140876/39815173-31cb0538-5365-11e8-82c9-2ff6afccad59.png)

Chaoslauncher then opens and when I click start, these are the errors i get (in order):
![image](https://user-images.githubusercontent.com/36140876/39815234-57e1dbac-5365-11e8-8b65-bc66472c8c53.png)

![image](https://user-images.githubusercontent.com/36140876/39815253-64fdf17c-5365-11e8-98e4-6f1bdd6c7da9.png)

Battle.net then opens but starcraft does not (I believe this could be a problem with the fact that im running the "latest" version of starcraft on battle.net and the chaoslauncher is trying to run an older version (maybe?)

![image](https://user-images.githubusercontent.com/36140876/39815398-dcdf0a64-5365-11e8-8369-8465c3192cf8.png)

And that is the final error, after this nothing happens. Hopefully this is helpful with troubleshooting and I hope we can figure this out, Thanks.

**Comment by dgant** [comment]
The "Ordinal 354" error is most frequently caused by using an unexpected version of StarCraft. BWAPI works only with StarCraft 1.16.1. The current free version is 1.18 and Remastered is 1.20, so you'll want to make sure you aren't using those.

BWMirror supports BWAPI 4.1.2 only. I'm not familiar with the starcraftai.com tutorial, but https://sscaitournament.com/index.php?action=tutorial should be a good BWMirror tutorial as well.

**Comment by dgant** [comment]
By the way, a potentially faster way to get help would be on Discord chat: https://discord.gg/urTTEY
