### ISSUE TITLE
Players incorrectly being reported as observers

### ISSUE THREAD

**Issue by adakitesystems** [bwapi/bwapi#790]
[Originally found](https://github.com/OpenBW/BWAPI4J/issues/38) by @Jabbo16 in BWAPI4J but traced to C++ BWAPI Client as the source issue. The following code reports all players as observers in client bots but the module bots report the players' statuses correctly.
```cpp
for (const auto p : Broodwar->getPlayers()) {
  std::cout << "Player: " << p->getName() << ": isObserver: " << p->isObserver() << std::endl;
}
```
BWAPI client versions 4.1.2, 4.2.0, and the current commit b36b208 are affected. I haven't tested earlier versions.

**Comment by EvanED** [comment]
You folks can test this far more easily than me, but maybe need something like

          StrCopy(p->name, i->getName());
          p->race = i->getRace();
          p->type = i->getType();
          p->force = getForceID(i->getForce());
          p->color = p2->color;
    +     p->isParticipating = p2->isParticipating;

in BWAPI\Source\BWAPI\Server.cpp around line 440?

(I checked all the other fields too -- the others are all copied either there or in the per-frame update.)

**Comment by adakitesystems** [comment]
It works. If this change is merged, it will only work for official versions higher than BWAPI 4.2.0 since a new BWAPI.dll is needed.

**Comment by EvanED** [comment]
I'll issue a PR this evening. Should it go to the `develop` branch?

One other thing I noticed. Ally/enemy information [is only copied once, at startup](https://github.com/bwapi/bwapi/blob/master/bwapi/BWAPI/Source/BWAPI/Server.cpp#L447). I imagine that, in theory, this could change, even though it won't for ladder/tournament play. Should that information be sent per-frame too?

**Comment by Jabbo16** [comment]
Yeah I think It should go to `develop`, good job!

**Comment by heinermann** [comment]
Issue fixed in PR.
