### ISSUE TITLE
How to specify the units of both sides of the battle

### ISSUE THREAD

**Issue by wanglin95** [bwapi/bwapi#800]
I want to obtain the respective winning rates in the case of the designated combat units on both sides，so，how to specify the units of both sides of the battle？

**Comment by N00byEdge** [comment]
Do you want a list of all units on both sides when doing replay analysis?

**Comment by wanglin95** [comment]
Not for replay analysis, I want to specify a list of combat units for both sides, then see which side can win. I want to get the winning rate.

**Comment by wanglin95** [comment]
How to use the StarCraft map editor  to create scenarios? I just learned BWAPI soon, can you please give me some advice? Thank you so much!

**Comment by dgant** [comment]
You can probably just open StarEdit and try using it. Or if you'd like you can search for StarEdit tutorials, if it helps. But it's unrelated to BWAPI. BWAPI just lets you control the player in a game.

**Comment by wanglin95** [comment]
Ok, I have another question. To ensure that the winning rate I get is reliable, and to avoid the impact of differences in operating levels, can I use the BWAPI built-in AI to meet the requirements?

**Comment by dgant** [comment]
BWAPI doesn't have a built-in AI, unless you mean ExampleAIModule which does nothing. BWAPI lets you write AIs.

StarCraft does have a built-in AI. You don't need BWAPI for that.

**Comment by wanglin95** [comment]
Then, if I want to finish my work, what should I do?

**Comment by dgant** [comment]
What's your work?

**Comment by wanglin95** [comment]
I want to specify a list of combat units for both sides, then see which side can win. I want to get the winning rate.
It contains two questions. First, to ensure that the level of players on both sides is the same, it is best to be a professional player. Second, how to specify the combat unit？

**Comment by wanglin95** [comment]
Ok, thank you so much. SparCraft may work, I will try it.

**Comment by wanglin95** [comment]
Where is StarEdit？ I can't find it.

**Comment by N00byEdge** [comment]
@wanglin95 FAP is a maintained alternative to SparCraft with more unit support. https://github.com/N00byEdge/FAP/
