### ISSUE TITLE
Request for new build

### ISSUE THREAD

**Issue by JohnWJackson** [bwapi/bwapi#802]
Getting the error:

fatal error C1047: The object or library file '..\lib\BWAPI.lib' was created with an older compiler than other objects; rebuild old objects and libraries

**Comment by heinermann** [comment]
Can you try [this build](https://ci.appveyor.com/project/heinermann/bwapi/build/4.2.0.107/artifacts)? It's using VS 2017 15.8.2.

**Comment by JohnWJackson** [comment]
That build worked for me. Thanks!
