### ISSUE TITLE
simulation platform

### ISSUE THREAD

**Issue by wanglin95** [bwapi/bwapi#803]
Except for SparCraft, does anyone know what else can be used to simulate combat?

**Comment by JasperGeurtz** [comment]
https://github.com/N00byEdge/FAP

**Comment by wanglin95** [comment]
Thank you very much, SparCraft supports very few units，so I want to know that how many types of units of Protoss can FAP support?

**Comment by Jabbo16** [comment]
JFAP if you use Java :relaxed:
https://github.com/Jabbo16/JFAP

**Comment by N00byEdge** [comment]
@wanglin95 FAP will support any units you can find in a game, or at least I'm not aware of any exceptions.

**Comment by wanglin95** [comment]
@N00byEdge Which version of VS did you use for FAP? I compiled it with VS2013, a lot of problems appeared. By the way, is there an introduction to the use of FAP? I need to use it urgently, but I feel it is a little difficult to do it by myself because there were too many problems.

**Comment by Jabbo16** [comment]
@wanglin95 FAP its C++17 and I think that latest bwapi also requires VS2017 to compile.

**Comment by wanglin95** [comment]
@N00byEdge In the NoLockup.cpp of the Tests project: #include "gtest/gtest.h",
the source file could not be opened, I can't find this file either. How to solve this problem?

**Comment by N00byEdge** [comment]
Install the gtest test adapter for VS.

**Comment by noname2534** [comment]
+1

**Comment by wanglin95** [comment]
@N00byEdge What is the search algorithm for players to perform actions in FAP? And which script is used?

**Comment by bftjoe** [comment]
No search, just attack nearest enemy.
