### ISSUE TITLE
Request new build (15.9.3)

### ISSUE THREAD

**Issue by s7jones** [bwapi/bwapi#818]
Hey all, if Appveyor is on VS15.9.3 is it possible to trigger a new build to get the latest files?

Cheers.

**Comment by N00byEdge** [comment]
Note to @heinermann : Triggering a rebuild on the `master` branch now will build the 4.3.0 code, not the official release, 4.2.0.

**Comment by bigheiniu** [comment]
Excuse me, how to use appveyor to generate new lib files. When I compile the file, it get "Specify which project or solution file to use because the folder contains more than one project or solution file." problem.
I compile on 4.3.0

**Comment by heinermann** [comment]
Try [these build artifacts](https://ci.appveyor.com/project/heinermann/bwapi/builds/22767843/artifacts) and report back.

**Comment by heinermann** [comment]
As of BWAPI 4.4, BWAPILIB is now included in bot projects so you should be able to compile it in your solution without having to need a new BWAPI build.
