### ISSUE TITLE
How to change a path 

### ISSUE THREAD

**Issue by kikwon** [bwapi/bwapi#819]
I tried to open ExampleProjects file in Release_Binary folder through VS 2017. However, it said the path is not correct. How can I change a path to open the ExampleAIClient, AIModuleLoader, ExampleAIModule, and ExampleTournamentModule projects? 

Is it fine to move ExampleProjects.sln to bwapi-master folder, instead of Release_Binary folder? It seems to work.

**Comment by heinermann** [comment]
That's odd, can you try again with [these build artifacts](https://ci.appveyor.com/project/heinermann/bwapi/builds/22767843/artifacts) and post a more detailed error message if one is available?

**Comment by heinermann** [comment]
I think the individual was using the BWAPII source code instead of the releases. Since there is no response I am closing the issue.
