### ISSUE TITLE
Cannot build in RELEASE

### ISSUE THREAD

**Issue by ChobitsTheZero** [bwapi/bwapi#821]
Have seen some other issue posts about this, just wondering if there is a fix/workaround for this? Haven't been able to solve it with any of the suggested workaround that I have found in other issue posts.

Error Message: Severity Code Description Project File Line Suppression State
Error C1047 The object or library file '..\lib\BWAPI.lib' was created with an older compiler than other objects; rebuild old objects and libraries ExampleAIClient D:\AI\BWAPI\ExampleAIClient\LINK 1

**Comment by heinermann** [comment]
I'll look into including BWAPILIB into all projects and just avoid lib linking entirely.

**Comment by ChobitsTheZero** [comment]
> I'll look into including BWAPILIB into all projects and just avoid lib linking entirely.

Sounds like a good plan. Thanks

**Comment by heinermann** [comment]
Please try the artifacts in [this build](https://ci.appveyor.com/project/heinermann/bwapi/builds/22767843/artifacts) and get back.

**Comment by heinermann** [comment]
As of BWAPI 4.4, BWAPILIB is now included in bot projects.
