### ISSUE TITLE
XCOPY error

### ISSUE THREAD

**Issue by ChobitsTheZero** [bwapi/bwapi#822]
Trying to resolve the "BWAPI.lib was created with older compiler" issue and following the steps mentioned in https://github.com/bwapi/bwapi/issues/797#issuecomment-414138781

I got stuck at the XCOPY error part, unsure how to resolve it.

**Comment by heinermann** [comment]
Hi can you try using the artifacts from [this build](https://ci.appveyor.com/project/heinermann/bwapi/builds/22767843/artifacts)?

**Comment by ChobitsTheZero** [comment]
> Hi can you try using the artifacts from [this build](https://ci.appveyor.com/project/heinermann/bwapi/builds/22767843/artifacts)?

Will give it a try, never used Appveyor before so not sure how it works.

**Comment by heinermann** [comment]
Well you don't need to use appveyor, you just need to download the provided artifacts (`BWAPI.7z` or `BWAPI_Setup.exe`).

**Comment by heinermann** [comment]
As of BWAPI 4.4, BWAPILIB can simply be included in your solution and is so in the example projects as an example. This should prevent the older compiler issue by simply recompiling BWAPILIB every time.
