### ISSUE TITLE
Best Route to upgrade project to 4.4.0

### ISSUE THREAD

**Issue by TheGeekiestOne** [bwapi/bwapi#830]
Hi there,

What will be the best way to tackle in upgrading a project using BWAPI 4.1.2 to version BWAPI 4.4.0?

**Comment by dgant** [comment]
The interfaces are pretty similar. The major changes are:
* Some types added/removed (For example, `PositionOrUnit` no longer exists -- those f unctions are represented a bit differently)
* Some C++17 language changes may invalidate C++14 syntax
* Latency compensation has been improved (this may *just work* but an existing bot relying on the older, buggier latency compensation may subtly misbehave -- you likely won't know without seeing a bunch of games)

I'd be inclined to just compile the project against BWAPI 4.4 and fix whatever errors that show up.
