### ISSUE TITLE
Investigate getting a code coverage metric for each test suite.

### ISSUE THREAD

**Issue by heinermann** [bwapi/bwapi#835]
i.e. maybe https://github.com/OpenCppCoverage/OpenCppCoverage ?

**Comment by ratiotile** [comment]
I have used OpenCppCoverage in the past and it works well.

**Comment by heinermann** [comment]
Went with `lcov` which offers line, function, and branch coverage. I think OpenCppCoverage only has line coverage? It doesn't really offer anything more in my opinion.  Since I'm publishing coverage results now, I am resolving this.
