### ISSUE TITLE
Bot crashes as soon as the game starts. Need help!

### ISSUE THREAD

**Issue by Sridhar54** [bwapi/bwapi#836]
![SharedScreenshot](https://user-images.githubusercontent.com/21017566/67160462-9566b880-f36e-11e9-8082-2d4850d0b1fc.jpg)
![SharedScreenshot2](https://user-images.githubusercontent.com/21017566/67160464-9ef02080-f36e-11e9-82cc-edd99c6641ef.jpg)

Running BroodwarBotQ using BWAPI3.7.4 and boost1.40.0. Game starts and even reads map and BWTA files are updated. After 10 seconds, the game crashes and i found these issues in debugging mode. Really need some help with this.

**Comment by Sridhar54** [comment]
@heinermann @N00byEdge any idea?

**Comment by heinermann** [comment]
Do you have source code? The stack trace shows it crashing in the bot DLL so it's probably not a BWAPI issue. Have you tried checking `etechestimator.cpp:93` and seeing what might go wrong? File permissions maybe?

**Comment by N00byEdge** [comment]
This is an error with the bot. You crash at https://github.com/syhw/BroodwarBotQ/blob/master/src/Intelligence/ETechEstimator.cpp#L93
because https://github.com/syhw/BroodwarBotQ/blob/master/src/Intelligence/ETechEstimator.cpp#L93 failed, which is probably due to this directory not existing: https://github.com/syhw/BroodwarBotQ/blob/master/src/Intelligence/ETechEstimator.cpp#L50
Please create a `bwapi-data/AI/tables/` directory.

**Comment by Sridhar54** [comment]
Thanks for the response. I checked the above points and i am getting the same set of errors even after that. What about the errors related to the boost library? Could anyone implement the bot and check whether everything is fine? Thanks

**Comment by N00byEdge** [comment]
Sorry, I don’t have an environment set up for testing that bot at this moment. Is it crashing at exactly the same line numbers related to that? If so, I just want you to make sure these paths are relative to your Starcraft directory.

**Comment by Sridhar54** [comment]
![debug1](https://user-images.githubusercontent.com/21017566/68543512-fe75a500-03dd-11ea-87e1-99bfc52371fd.jpg)
![debug2](https://user-images.githubusercontent.com/21017566/68543513-ff0e3b80-03dd-11ea-9747-a7de378a0142.jpg)
While running in debug setup, i am getting this message related to MSVCR90D.dll. Any inputs?

**Comment by Sridhar54** [comment]
After making a few changes, i am getting errors when choosing different races for opposition. For example: https://github.com/syhw/BroodwarBotQ/blob/71053d943d1bfb4cbf5a687bb015362decd9428c/src/Intelligence/ETechEstimator.cpp#L59 I am getting error here for terran bot.
@N00byEdge can you just see this

**Comment by N00byEdge** [comment]
Sure, I am seeing this. I'm not sure what you want me to do though. This doesn't seem like a BWAPI issue. I don't have a crash report/line numbers or anything. Maybe try running as admin as that directory might be inside your programs folder and therefore it might not be able to edit that?

**Comment by Sridhar54** [comment]
Sorry for posting in BWAPI issues. I did not know where to find the answer for this. Thanks for the responses.

**Comment by dgant** [comment]
@Sridhar54 a better source for non-BWAPI questions is Discord: https://discord.gg/sHPYQqN

**Comment by Sridhar54** [comment]
@dgant Thanks for the information!!
