### ISSUE TITLE
Include Resolution Expander

### ISSUE THREAD

**Issue by dgant** [bwapi/bwapi#838]
Resolution Expander stretches the visible field of the StarCraft Window past 640x480. This would be nice to have because the larger field of view makes it easier to see what your bot is doing.

SSCAIT has been using Resolution Expander for years. This also demonstrates that it works correctly with BWAPI draw commands.

https://www.ghoztcraft.net/forums/files/file/1412-resolution-expander/
https://tl.net/forum/brood-war/97122-custom-resolution-hack?page=9#174

![image](https://user-images.githubusercontent.com/116363/68247512-ff2ac780-ffe8-11e9-8221-e96c0add0697.png)

**Comment by heinermann** [comment]
This is resolved by 9b871e212e1557f49eac314d888b75a5bfb6c9e3
