### ISSUE TITLE
Add speedUpgrade field to UnitType

### ISSUE THREAD

**Issue by N00byEdge** [bwapi/bwapi#842]
There is no easy way to check which upgrade upgrades the speed of a unit, not even the `upgrades()` function does that. You can get the speed of a unit through the player, but that's obviously a very clunky interface for some usages.

**Comment by dgant** [comment]
Ditto attack speed and attack range upgrade

**Comment by N00byEdge** [comment]
I made an issue for attack speed. Attack range can affect only one weapon though, so I'm not sure if we want that one on the unit.
