### ISSUE TITLE
isGatheringMinerals issue with LatCom on [upgrading from 4.1.2->4.4]

### ISSUE THREAD

**Issue by JasperGeurtz** [bwapi/bwapi#844]
### Issue
Based on the issue reported here https://github.com/JavaBWAPI/JBWAPI/issues/48 . It is likely that there has been a change in how the isGatheringMinerals flag (maybe more?) behaves in BWAPI 4.4 compared to BWAPI 4.1.2.

With LatCom enabled, in this case with 2 frames of latency, a worker that has been given the order to mine a mineral on frame 0, will say `isGatheringMinerals==true` for frames 0 and 1 but not for frame 2 (it becomes `false`). Afterwards from frame 3 on it becomes `true` again.

### Expected behavior
In version 4.1.2 it was `true` for all the frames (which is expected)

### Code to reproduce
```cpp
#include <BWAPI.h>
#include <BWAPI/Client.h>
#include <iostream>
#include <thread>
#include <chrono>

using namespace BWAPI;

int main() {
	std::cout << "Connecting..." << std::endl;
	while (!BWAPIClient.connect()) {
		std::this_thread::sleep_for(std::chrono::milliseconds{ 1000 });
	}
	while ( !Broodwar->isInGame() ) {
		BWAPI::BWAPIClient.update();
	}
	std::cout << "Connected" << std::endl;
	Unitset units = Broodwar->self()->getUnits();
	Unitset minerals  = Broodwar->getMinerals();
	for (auto &u : units){
		if (u->getType().isWorker()) {
			Unit closestMineral = nullptr;

			for (auto &m : minerals) {
				if ( !closestMineral || u->getDistance(m) < u->getDistance(closestMineral)) {
					closestMineral = m;
				}
			}
			u->gather(closestMineral);
		}
	}
	std::cout << "latcom: " << Broodwar->isLatComEnabled() << "\n";
	std::cout << "latcom frames: " << Broodwar->getLatencyFrames() << "\n";


	while(Broodwar->isInGame()) {
		for(auto &e : Broodwar->getEvents()) {
			switch(e.getType()) {
				case EventType::MatchFrame:
					if (Broodwar->getFrameCount() > 3) {
						return 0; //exit after 
					}
					std::cout << "FRAME: " << Broodwar->getFrameCount() << "\n";
					for (auto &u : units) {
						if (u->getType().isWorker()) {
							std::cout << "Worker :" << u->getID() << "\n";
							std::cout << "idle :" << u->isIdle() << "\n";
							std::cout << "order :" << u->getOrder() << "\n";
							std::cout << "isGatheringMinerals :" << u->isGatheringMinerals() << "\n";
							std::cout << "orderTarget :" << u->getOrderTarget() << "\n";
							break;
						}
					}
					break;
			}
		}
		BWAPI::BWAPIClient.update();
	}
	return 0;
}
```

### Sample output

![2019-12-17 19_07_16 - Copy](https://user-images.githubusercontent.com/10107858/71018850-e6dabc00-2101-11ea-93f2-224b867f9297.png)

**Comment by Jabbo16** [comment]
I noticed the same behaviour in BWAPI 4.3 with latcom on/off, I guess its something related to the latcom rewrite introduced in that version.

**Comment by N00byEdge** [comment]
Yeah, the latcom is definitely it. Looks like the latcom is ending one frame too early for this command. Mind testing #845 and seeing if it fixes the issue?

**Comment by JasperGeurtz** [comment]
![2019-12-18 11_51_23](https://user-images.githubusercontent.com/10107858/71075521-e2a7b080-218c-11ea-9d4a-27f8c47cc16e.png)

Yes that fixes it!

Another question, why is OrderTarget a nullpointer on frame 1, while the isGathering etc. is true

**Comment by N00byEdge** [comment]
Latcom won't set target pointers since we can't know for sure until the game tells us.
This could be changed to use speculative targets, but I kept the behaviour that we had before.
