### ISSUE TITLE
No server proc ID error on Java

### ISSUE THREAD

**Issue by Willskull** [bwapi/bwapi#846]
I am in the process of trying to make an AI for a class project, one which used to be very common in the past. However all the tutorials I have found for the Java installation haven't told me how to deal with the errors I am receiving. The most recent is the "No server proc ID" error.

Bellow is my output: 

Connecting to Broodwar...
Game table mapping not found.
Game table mapping not found.
No server proc ID
0 | 15780 | 0 | 897015
1 | 4294967295 | 0 | 0
2 | 4294967295 | 0 | 0
3 | 4294967295 | 0 | 0
4 | 4294967295 | 0 | 0
5 | 4294967295 | 0 | 0
6 | 4294967295 | 0 | 0
7 | 4294967295 | 0 | 0
No server proc ID
0 | 15780 | 0 | 897015
1 | 4294967295 | 0 | 0
2 | 4294967295 | 0 | 0
3 | 4294967295 | 0 | 0
4 | 4294967295 | 0 | 0
5 | 4294967295 | 0 | 0
6 | 4294967295 | 0 | 0
7 | 4294967295 | 0 | 0
No server proc ID
0 | 15780 | 0 | 897015
1 | 4294967295 | 0 | 0
2 | 4294967295 | 0 | 0
3 | 4294967295 | 0 | 0
4 | 4294967295 | 0 | 0
5 | 4294967295 | 0 | 0
6 | 4294967295 | 0 | 0
7 | 4294967295 | 0 | 0
0 | 15780 | 0 | 899609
No server proc ID
1 | 4294967295 | 0 | 0
2 | 4294967295 | 0 | 0
3 | 4294967295 | 0 | 0
4 | 4294967295 | 0 | 0
5 | 4294967295 | 0 | 0
6 | 4294967295 | 0 | 0
7 | 4294967295 | 0 | 0
No server proc ID
0 | 15780 | 0 | 899609
1 | 4294967295 | 0 | 0
2 | 4294967295 | 0 | 0
3 | 4294967295 | 0 | 0
4 | 4294967295 | 0 | 0
5 | 4294967295 | 0 | 0
6 | 4294967295 | 0 | 0
7 | 4294967295 | 0 | 0
No server proc ID
0 | 15780 | 0 | 899609
1 | 4294967295 | 0 | 0
2 | 4294967295 | 0 | 0
3 | 4294967295 | 0 | 0
4 | 4294967295 | 0 | 0
5 | 4294967295 | 0 | 0
6 | 4294967295 | 0 | 0
7 | 4294967295 | 0 | 0
0 | 15780 | 0 | 899609
1 | 4294967295 | 0 | 0
2 | 4294967295 | 0 | 0
3 | 4294967295 | 0 | 0
4 | 4294967295 | 0 | 0
5 | 4294967295 | 0 | 0
6 | 4294967295 | 0 | 0
7 | 4294967295 | 0 | 0
No server proc ID
No server proc ID
0 | 15780 | 0 | 899609
1 | 4294967295 | 0 | 0
2 | 4294967295 | 0 | 0
3 | 4294967295 | 0 | 0
4 | 4294967295 | 0 | 0
5 | 4294967295 | 0 | 0
6 | 4294967295 | 0 | 0
7 | 4294967295 | 0 | 0
No server proc ID
0 | 15780 | 0 | 899609
1 | 4294967295 | 0 | 0
2 | 4294967295 | 0 | 0
3 | 4294967295 | 0 | 0
4 | 4294967295 | 0 | 0
5 | 4294967295 | 0 | 0
6 | 4294967295 | 0 | 0
7 | 4294967295 | 0 | 0
No server proc ID
0 | 15780 | 0 | 899609
1 | 4294967295 | 0 | 0
2 | 4294967295 | 0 | 0
3 | 4294967295 | 0 | 0
4 | 4294967295 | 0 | 0
5 | 4294967295 | 0 | 0
6 | 4294967295 | 0 | 0
7 | 4294967295 | 0 | 0
No server proc ID
0 | 15780 | 0 | 899609
1 | 4294967295 | 0 | 0
2 | 4294967295 | 0 | 0
3 | 4294967295 | 0 | 0
4 | 4294967295 | 0 | 0
5 | 4294967295 | 0 | 0
6 | 4294967295 | 0 | 0
7 | 4294967295 | 0 | 0
No server proc ID
0 | 15780 | 0 | 899609
1 | 4294967295 | 0 | 0
2 | 4294967295 | 0 | 0
3 | 4294967295 | 0 | 0
4 | 4294967295 | 0 | 0
5 | 4294967295 | 0 | 0
6 | 4294967295 | 0 | 0
7 | 4294967295 | 0 | 0
0 | 15780 | 0 | 899609
1 | 4294967295 | 0 | 0
2 | 4294967295 | 0 | 0
3 | 4294967295 | 0 | 0
4 | 4294967295 | 0 | 0
5 | 4294967295 | 0 | 0
6 | 4294967295 | 0 | 0
7 | 4294967295 | 0 | 0
No server proc ID
No server proc ID
0 | 15780 | 0 | 899609
1 | 4294967295 | 0 | 0
2 | 4294967295 | 0 | 0
3 | 4294967295 | 0 | 0
4 | 4294967295 | 0 | 0
5 | 4294967295 | 0 | 0
6 | 4294967295 | 0 | 0
7 | 4294967295 | 0 | 0
No server proc ID
0 | 15780 | 0 | 899609
1 | 4294967295 | 0 | 0
2 | 4294967295 | 0 | 0
3 | 4294967295 | 0 | 0
4 | 4294967295 | 0 | 0
5 | 4294967295 | 0 | 0
6 | 4294967295 | 0 | 0
7 | 4294967295 | 0 | 0
0 | 15780 | 0 | 899609
1 | 4294967295 | 0 | 0
2 | 4294967295 | 0 | 0
3 | 4294967295 | 0 | 0
4 | 4294967295 | 0 | 0
5 | 4294967295 | 0 | 0
6 | 4294967295 | 0 | 0
7 | 4294967295 | 0 | 0
No server proc ID
0 | 15780 | 0 | 899609
1 | 4294967295 | 0 | 0
2 | 4294967295 | 0 | 0
3 | 4294967295 | 0 | 0
4 | 4294967295 | 0 | 0
5 | 4294967295 | 0 | 0
6 | 4294967295 | 0 | 0
7 | 4294967295 | 0 | 0
No server proc ID
0 | 15780 | 0 | 899609
1 | 4294967295 | 0 | 0
2 | 4294967295 | 0 | 0
3 | 4294967295 | 0 | 0
4 | 4294967295 | 0 | 0
5 | 4294967295 | 0 | 0
6 | 4294967295 | 0 | 0
7 | 4294967295 | 0 | 0
No server proc ID

**Comment by N00byEdge** [comment]
You mention you're using Java. You should open an issue on your Java APIs (there are a few) github, this is the C++ BWAPI/server Github.

But in general:
Make sure your BWAPI client version matches the server used. It seems that your BWAPI server was running at some point, but I guess it could have quit/crashed/stopped responding. Could you please provide us with the name of the Java API you are using, along with versions of both that and BWAPI server?

**Comment by Willskull** [comment]
I followed the tutorial on this website https://sscaitournament.com/index.php?action=tutorial which uses the BWMirror API I believe.

**Comment by dgant** [comment]
BWMirror requires BWAPI 4.1.2. Make sure that's the BWAPI version you're using.

[JBWAPI](https://github.com/JavaBWAPI/JBWAPI/) is a modern, updated version of BWMirror that uses the latest BWAPI version. I endorse its use.

Feel free to stop by the [Brood War AI Discord](https://discord.gg/DqvHsq9) for any questions!

**Comment by JasperGeurtz** [comment]
You couls try to follow this tutorial:
https://github.com/JavaBWAPI/Java-BWAPI-Tutorial/wiki/Setup

**Comment by N00byEdge** [comment]
The BWAPI link on the Java tutorial page links to 4.4.0, which may or may not be an issue.
