### ISSUE TITLE
can see gas in enemy geyser

### ISSUE THREAD

**Issue by jjs47** [bwapi/bwapi#847]
When I call unit->getResources() on a visible enemy refinery building, I get a correct up-to-date answer. Human players only get to see gas amounts for bare geysers and their own refineries.

I only tried in BWAPI 4.1.2, but I don't see any related issues or changelog entries so I expect it survives in later versions.

**Comment by heinermann** [comment]
Yep that's a miss.

**Comment by Jabbo16** [comment]
Cant replicate with fresh BWAPI 4.4 from SSCAIT

![image](https://user-images.githubusercontent.com/17556613/72996486-1b295280-3dfb-11ea-8356-3f28763ebd4a.png)

Code:

```cpp
for (auto& u : Broodwar->getAllUnits()) {
    if (u->getPlayer()->isEnemy(Broodwar->self()) && u->getType().isRefinery()) {
        std::string s = std::to_string(u->getInitialResources());
        std::string s2 = std::to_string(u->getResources());
        Broodwar->drawTextMap(u->getInitialPosition(), s.c_str(), Colors::White);
        Broodwar->drawTextMap(u->getInitialPosition() + Position(0, 16), s.c_str(), Colors::White);
    }
}
```

**Comment by Jabbo16** [comment]
Can confirm It happens with fresh BWAPI 4.4 from SSCAIT

![image](https://user-images.githubusercontent.com/17556613/72996870-b7ebf000-3dfb-11ea-924a-2ca902416860.png)
