### ISSUE TITLE
Player::getRace doesn't update for Client Bots

### ISSUE THREAD

**Issue by JasperGeurtz** [bwapi/bwapi#851]
https://bwapi.github.io/class_b_w_a_p_i_1_1_player_interface.html#a169afa32d319a4f065a8d7aa56fac052

mentions that 
```
Return values
  Races::Unknown If the player chose Races::Random when the game started and they have not been seen.
```

However when running a Client bot against an opponent that selected Random, getRace() keeps returning `Unknown` even after seeing some of the enemy units

**Comment by heinermann** [comment]
This is fixed in 82ce2e7e4b958052a4f72eb7965769dc25221e27
