### ISSUE TITLE
bwapi.github.io out of date

### ISSUE THREAD

**Issue by bftjoe** [bwapi/bwapi#854]
Please update, it still says to use VS 2013

https://bwapi.github.io/

**Comment by N00byEdge** [comment]
It's not only that, it's still running the 4.2.0 docs. This should probably be prioritized.

**Comment by bftjoe** [comment]
@heinermann adam pls

**Comment by bftjoe** [comment]
https://github.com/bwapi/bwapi.github.io/pull/1

**Comment by N00byEdge** [comment]
Let's continue this discussion in the linked issue.
