### ISSUE TITLE
my bwapi 4.4.0 crashes in the beginning

### ISSUE THREAD

**Issue by bean-gno** [bwapi/bwapi#856]
Hi! I'm interested in reinforcement learning and I'm trying to taste what it's like to use AI in real world so I'm using Starcraft as a start.

I installed the starcraft 1.16.1 version from the web and bwapi 4.4.0 version on the same drive, and OS is windows 10
I think I followed the instructions on readme, but when I start starcraft it says

![image](https://user-images.githubusercontent.com/48382910/82666671-559fe080-9c71-11ea-96e4-10ca3b7561ad.png)

and when I start a custom game api vs bw AI,
it crashes and a message pops up saying some command referred to some memory 0x000000~~~~~~, and that memory cannot be read.

Can anybody help me with this problem?
Thanks

**Comment by chriscoxe** [comment]
This happens if you don't start Chaoslauncher as an Administrator.  Always start it as an Administrator (e.g. in Windows Explorer, right-click on Chaoslauncher.exe -> "Run as administrator").  If that still doesn't help, perhaps there is a problem with one or more of the .bwl files in Chaoslauncher's "Plugins" folder.

**Comment by bean-gno** [comment]
I did launch chaoslauncher as admin the first time.
It works now, and I think the problem was that the platform toolset was set to windows XP setting when building the aimodule in visual studio.
And also I ran it on 'debug' mode.

**Comment by bean-gno** [comment]
> This happens if you don't start Chaoslauncher as an Administrator. Always start it as an Administrator (e.g. in Windows Explorer, right-click on Chaoslauncher.exe -> "Run as administrator"). If that still doesn't help, perhaps there is a problem with one or more of the .bwl files in Chaoslauncher's "Plugins" folder.

**Comment by dgant** [comment]
Yep, if the bot DLL is compiled as debug, you need to run the Debug BWAPI plug in, and vice-versa. A mismatch will cause an error.

**Comment by heinermann** [comment]
Is this resolved now?

**Comment by bean-gno** [comment]
I think so, it was quite some time ago!!!
