### ISSUE TITLE
Errors when starting Starcraft from Chaoslauncher

### ISSUE THREAD

**Issue by MrTate** [bwapi/bwapi#858]
I'm following the Java tutorial here: https://sscaitournament.com/index.php?action=tutorial&fbclid=IwAR0_rNKoHj6ox31GyzSjcX7jGB2zPI2UamuQoK8NebZN_5Lf2C7itx-O8Xk

I have the eclipse workspace setup, I click run, and I'm getting the "Game table mapping not found" as expected.

I run Chaoslauncher as administrator. I have the BWAPI 4.4.0 Injector [RELEASE] selected as well as the W-MODE 1.02 and Starcraft 1.16.1 selected. When I press start I see the following error messages:

![Error1](https://user-images.githubusercontent.com/20361370/84098674-b98a0f00-a9bc-11ea-9e5a-f6e62144bc26.jpg)
![Error2](https://user-images.githubusercontent.com/20361370/84098682-be4ec300-a9bc-11ea-8c4d-ce3f6aafe0d8.jpg)

Starcraft launches successfully when but whenever I start a game nothing happens, the "Game table mapping not found" is always printed in the Eclipse console.

**Comment by MrTate** [comment]
So I was able to get past this by installing them on the same drive, however. When launching Starcraft I get the following console log message:

Connected
Error: Client and Server are not compatible!
Client Revision: 4708
Server Revision: 10003

**Comment by dgant** [comment]
That error comes from your installed BWAPI.dll version mismatching your Java API version.

I recommend using BWAPI 4.4 and the latest JBWAPI, which also uses BWAPI 4.4

**Comment by MrTate** [comment]
Resolved this with JBWAPI and the tutorial
