### ISSUE TITLE
Starcraft is started in battle.net now, is the tool still working?

### ISSUE THREAD

**Issue by playgithub** [bwapi/bwapi#894]

**Comment by dgant** [comment]
What exactly does that mean? You start the game through ChaosLauncher and the game goes directly to Battle.net? If so the most likely reason is that your BWAPI.ini has `auto_menu = BATTLE_NET `

You may get faster answers to your questions on Discord: https://discord.gg/DqvHsq9

**Comment by playgithub** [comment]
> I suspect they are asking regarding Starcraft: Remastered. BWAPI is not compatible with Starcraft: Remastered, but instead works with version 1.16 using Chaos Launcher as dgant said above.

Yes, thanks.
