### ISSUE TITLE
Lack of data?

### ISSUE THREAD

**Issue by playgithub** [bwapi/bwapi#895]
e.g. for zealot

https://bwapi.github.io/namespace_b_w_a_p_i_1_1_unit_types.html#a3225ed6fc5c361a8ba035c1d4c96f3c3

lack of
* cool time, i.e. time between continuous attack
* normal speed, i.e. speed before upgrading

**Comment by dgant** [comment]
> cool time, i.e. time between continuous attack
This is part of weapon data

> normal speed, i.e. speed before upgrading
All movement speed upgrades give a 50% bonus

**Comment by dgant** [comment]
I encourage you to use Discord for asking questions like these. You will get answers faster and produce fewer artifacts on the repository.

**Comment by playgithub** [comment]
OK, thanks.
