### ISSUE TITLE
Terran_Barracks unit said unable to train

### ISSUE THREAD

**Issue by Diamondemon** [bwapi/bwapi#901]
Hello,

I don't know if this is intentional, but when using the `canTrain()` function on a `Terran_Barracks` unit, it returns false, whereas when I use the `canTrain(BWAPI::UnitTypes::Terran_Marine)` it returns true.

Thankfully I can workaround but I have some buildings that I don't want to see bothering about the building list, and since the short overload is not reliable, I'm kind of bothered.

**Comment by Diamondemon** [comment]
Wait, I may have been not specific enough on my question:

This is what I have so far with my tests:
```
someBarracks->canTrain(Terran_Marine) == true
someBarracks->canTrain() == false
someCommandCenter->canTrain(Terran_Marine) == true
```

**Comment by dgant** [comment]
canTrain() can return false depending on the state of the unit at the time you invoke it. For example, incomplete or floating Barracks can not train units.  You can't train a Marine if you have no minerals. See https://github.com/bwapi/bwapi/blob/3438abd8e0222f37934ba62b2130c3933b067678/bwapi/Shared/Templates.h#L874 for the full considerations.

As for your Command Center, I suspect the most likely cause is the variable you think is referring to a Command Center actually referring to a Barracks. A bug of this nature seems very unlikely. I would double check the identity of the unit to be sure.

**Comment by Diamondemon** [comment]
I'm surprised myself, to be honest.

Here is what my debugger says, when the `onUnitComplete(BWAPI::Unit unit)` is called (so all following tests are done in the same scope)

```
unit->getType() == 106
unit->canTrain(BWAPI::UnitTypes::Terran_Marine, true, true) == true
unit->canTrain(true)
```

I think unit with id 106 is the `Terran_Command_Center`, am I wrong?

**Comment by Diamondemon** [comment]
It's good to know for anyone using the debugger to find the reason of their bug.

I found the actual problem in my recruitment process elsewhere, so yeah, I was misled.

I'm closing this since the issue is not relevant for the BWAPI. Thanks for your dedication.

**Comment by dgant** [comment]
If you need a handy ID -> type lookup while debugging you can use https://docs.google.com/spreadsheets/d/1jlYDkXW2pQey1oGJlQRBiGjdMs0kfrdHAwzVI2zAjrU/edit
