### ISSUE TITLE
Protoss Assimilator does not fire created even due to wasAlive flag set to true when first created (fix included in issue)

### ISSUE THREAD

**Issue by wojcikp** [bwapi/bwapi#903]
When a Protoss Assimilator is first created  (first time seen in BW::BWDATA::UnitNodeList_VisibleUnit_First) then the wasAlive flag is already set to true meaning the creation does not fire the created event (however completed event is correctly fired).

To fix this issue I made the following changes (files also attached following):

## GameImpl.h
top of file (after `#include <deque>`)
    `#include <unordered_map>`

define container for tracked assimilators (after `std::vector<PlayerImpl*> droppedPlayers;`):
    `std::unordered_map<int, UnitImpl*> knownAssimilators;`

## GameInternals.cpp
clear the container (in the `// clear all sets` section where other containers are cleared):
    `this->knownAssimilators.clear();`

## GameUnits.cpp
in method `void GameImpl::computeUnitExistence()` in the for loop 
`for ( UnitImpl* u = UnitImpl::BWUnitToBWAPIUnit(BW::BWDATA::UnitNodeList_VisibleUnit_First); u; u = u->getNext() )`

add the following code before the `if ( isUnitAlive(u) )` statement

```
// There is a bug in StartCraft where assimilators are created with the 
// wasAlive set to true causing Event::Create not to fire. We spoof
// that event by keeping track of the first time an assimilator is seen
// based on unit ID.
if (((BW::CUnit*)u->getOriginalRawData)->unitType == UnitTypes::Protoss_Assimilator)
{
  if (knownAssimilators.find(u->id) == knownAssimilators.end())
  {
    // This is a new assimilator so reset wasAlive flag
    u->wasAlive = false;

    // Add to known list
    knownAssimilators.insert_or_assign(u->id, u);
  }
}
```
in method `void GameImpl::computePrimaryUnitSets()` after the line `events.push_back(Event::UnitDestroy(u));` 
add the following code

```
// Was it an assimilator that died?
if (ui->getType() == UnitTypes::Protoss_Assimilator)
{
  // The assimilator has died, remove it from known list
  knownAssimilators.erase(u->id);
}
```
---
**NOTE**
.txt versions of updated files included
---

[GameImpl.h.txt](https://github.com/bwapi/bwapi/files/11027031/GameImpl.h.txt)
[GameInternals.cpp.txt](https://github.com/bwapi/bwapi/files/11027032/GameInternals.cpp.txt)
[GameUnits.cpp.txt](https://github.com/bwapi/bwapi/files/11027034/GameUnits.cpp.txt)

**Comment by wojcikp** [comment]
Interesting, I will test that and if so mark it here. It makes sense what you are saying for sure! 

I have only ever used BWAPI as Protoss so not sure for other races if same behavior!

**Comment by wojcikp** [comment]
Well thank you @NiteKat  you are 100% correct! The issue I have raised is is not a bug, you use the morph event to detect creation of an assimilator. 

Sigh, at least I have a much better idea about how the injected hacks work

**Comment by NiteKat** [comment]
If I recall correctly, there's also an oddity when a gas structure is destroyed. So the Gesyer morphs into the gas structure, but when it's destroyed or cancelled, I believe a new Geyser is created and assigned a new ID in BWAPI and triggers unit create? I might have a detail off there, but just a heads up that there's also another "not intuitive" situation there thanks to the internals of Brood War.
